// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(clippy::all)]
use ::bitflags::bitflags;
use bytes::{Buf, BufMut};
use super::*;
use super::super::types::*;
use crate::bedrock::codec::BedrockCodec;
pub use crate::bedrock::protocol::v1_18_30::PacketStartGameDimension as PacketStartGameDimension;
pub use crate::bedrock::protocol::v1_21_80::PacketStartGameEditorWorldType as PacketStartGameEditorWorldType;
pub use crate::bedrock::protocol::v1_19_20::PacketStartGameChatRestrictionLevel as PacketStartGameChatRestrictionLevel;
#[derive(Debug, Clone, PartialEq)]
pub struct PacketStartGame {
    pub entity_id: i64,
    pub runtime_entity_id: i64,
    pub player_gamemode: GameMode,
    pub player_position: Vec3F,
    pub rotation: Vec2F,
    pub seed: u64,
    pub biome_type: i16,
    pub biome_name: String,
    pub dimension: PacketStartGameDimension,
    pub generator: i32,
    pub world_gamemode: GameMode,
    pub hardcore: bool,
    pub difficulty: i32,
    pub spawn_position: BlockCoordinates,
    pub achievements_disabled: bool,
    pub editor_world_type: PacketStartGameEditorWorldType,
    pub created_in_editor: bool,
    pub exported_from_editor: bool,
    pub day_cycle_stop_time: i32,
    pub edu_offer: i32,
    pub edu_features_enabled: bool,
    pub edu_product_uuid: String,
    pub rain_level: f32,
    pub lightning_level: f32,
    pub has_confirmed_platform_locked_content: bool,
    pub is_multiplayer: bool,
    pub broadcast_to_lan: bool,
    pub xbox_live_broadcast_mode: i32,
    pub platform_broadcast_mode: i32,
    pub enable_commands: bool,
    pub is_texturepacks_required: bool,
    pub gamerules: GameRules,
    pub experiments: Experiments,
    pub experiments_previously_used: bool,
    pub bonus_chest: bool,
    pub map_enabled: bool,
    pub permission_level: PermissionLevel,
    pub server_chunk_tick_range: i32,
    pub has_locked_behavior_pack: bool,
    pub has_locked_resource_pack: bool,
    pub is_from_locked_world_template: bool,
    pub msa_gamertags_only: bool,
    pub is_from_world_template: bool,
    pub is_world_template_option_locked: bool,
    pub only_spawn_v_1_villagers: bool,
    pub persona_disabled: bool,
    pub custom_skins_disabled: bool,
    pub emote_chat_muted: bool,
    pub game_version: String,
    pub limited_world_width: i32,
    pub limited_world_length: i32,
    pub is_new_nether: bool,
    pub edu_resource_uri: EducationSharedResourceUri,
    pub experimental_gameplay_override: bool,
    pub chat_restriction_level: PacketStartGameChatRestrictionLevel,
    pub disable_player_interactions: bool,
    pub server_identifier: String,
    pub world_identifier: String,
    pub scenario_identifier: String,
    pub owner_identifier: String,
    pub level_id: String,
    pub world_name: String,
    pub premium_world_template_id: String,
    pub is_trial: bool,
    pub rewind_history_size: i32,
    pub server_authoritative_block_breaking: bool,
    pub current_tick: i64,
    pub enchantment_seed: i32,
    pub block_properties: BlockProperties,
    pub multiplayer_correlation_id: String,
    pub server_authoritative_inventory: bool,
    pub engine: String,
    pub property_data: Vec<u8>,
    pub block_pallette_checksum: u64,
    pub world_template_id: uuid::Uuid,
    pub client_side_generation: bool,
    pub block_network_ids_are_hashes: bool,
    pub tick_death_systems: bool,
    pub server_controlled_sound: bool,
}
impl crate::bedrock::codec::BedrockCodec for PacketStartGame {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        crate::bedrock::codec::ZigZag64(self.entity_id).encode(buf)?;
        crate::bedrock::codec::VarLong(self.runtime_entity_id).encode(buf)?;
        self.player_gamemode.encode(buf)?;
        self.player_position.encode(buf)?;
        self.rotation.encode(buf)?;
        crate::bedrock::codec::U64LE(self.seed).encode(buf)?;
        crate::bedrock::codec::I16LE(self.biome_type).encode(buf)?;
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.biome_name)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.biome_name).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        self.dimension.encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.generator).encode(buf)?;
        self.world_gamemode.encode(buf)?;
        self.hardcore.encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.difficulty).encode(buf)?;
        self.spawn_position.encode(buf)?;
        self.achievements_disabled.encode(buf)?;
        self.editor_world_type.encode(buf)?;
        self.created_in_editor.encode(buf)?;
        self.exported_from_editor.encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.day_cycle_stop_time).encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.edu_offer).encode(buf)?;
        self.edu_features_enabled.encode(buf)?;
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.edu_product_uuid)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.edu_product_uuid).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        crate::bedrock::codec::F32LE(self.rain_level).encode(buf)?;
        crate::bedrock::codec::F32LE(self.lightning_level).encode(buf)?;
        self.has_confirmed_platform_locked_content.encode(buf)?;
        self.is_multiplayer.encode(buf)?;
        self.broadcast_to_lan.encode(buf)?;
        crate::bedrock::codec::VarInt(self.xbox_live_broadcast_mode).encode(buf)?;
        crate::bedrock::codec::VarInt(self.platform_broadcast_mode).encode(buf)?;
        self.enable_commands.encode(buf)?;
        self.is_texturepacks_required.encode(buf)?;
        let len = self.gamerules.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        for item in &self.gamerules {
            item.encode(buf)?;
        }
        let len = self.experiments.len();
        crate::bedrock::codec::I32LE(len as i32).encode(buf)?;
        for item in &self.experiments {
            item.encode(buf)?;
        }
        self.experiments_previously_used.encode(buf)?;
        self.bonus_chest.encode(buf)?;
        self.map_enabled.encode(buf)?;
        self.permission_level.encode(buf)?;
        crate::bedrock::codec::I32LE(self.server_chunk_tick_range).encode(buf)?;
        self.has_locked_behavior_pack.encode(buf)?;
        self.has_locked_resource_pack.encode(buf)?;
        self.is_from_locked_world_template.encode(buf)?;
        self.msa_gamertags_only.encode(buf)?;
        self.is_from_world_template.encode(buf)?;
        self.is_world_template_option_locked.encode(buf)?;
        self.only_spawn_v_1_villagers.encode(buf)?;
        self.persona_disabled.encode(buf)?;
        self.custom_skins_disabled.encode(buf)?;
        self.emote_chat_muted.encode(buf)?;
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.game_version)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.game_version).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        crate::bedrock::codec::I32LE(self.limited_world_width).encode(buf)?;
        crate::bedrock::codec::I32LE(self.limited_world_length).encode(buf)?;
        self.is_new_nether.encode(buf)?;
        self.edu_resource_uri.encode(buf)?;
        self.experimental_gameplay_override.encode(buf)?;
        self.chat_restriction_level.encode(buf)?;
        self.disable_player_interactions.encode(buf)?;
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.server_identifier)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.server_identifier).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.world_identifier)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.world_identifier).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.scenario_identifier)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.scenario_identifier).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.owner_identifier)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.owner_identifier).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.level_id)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.level_id).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.world_name)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.world_name).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.premium_world_template_id)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.premium_world_template_id).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        self.is_trial.encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.rewind_history_size).encode(buf)?;
        self.server_authoritative_block_breaking.encode(buf)?;
        crate::bedrock::codec::I64LE(self.current_tick).encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.enchantment_seed).encode(buf)?;
        let len = self.block_properties.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        for item in &self.block_properties {
            item.encode(buf)?;
        }
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.multiplayer_correlation_id)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.multiplayer_correlation_id).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        self.server_authoritative_inventory.encode(buf)?;
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.engine)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.engine).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        self.property_data.encode(buf)?;
        crate::bedrock::codec::U64LE(self.block_pallette_checksum).encode(buf)?;
        self.world_template_id.encode(buf)?;
        self.client_side_generation.encode(buf)?;
        self.block_network_ids_are_hashes.encode(buf)?;
        self.tick_death_systems.encode(buf)?;
        self.server_controlled_sound.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let entity_id = <crate::bedrock::codec::ZigZag64 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let runtime_entity_id = <crate::bedrock::codec::VarLong as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let player_gamemode = <GameMode as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let player_position = <Vec3F as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let rotation = <Vec2F as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let seed = <crate::bedrock::codec::U64LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let biome_type = <crate::bedrock::codec::I16LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let biome_name = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let dimension = <PacketStartGameDimension as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let generator = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let world_gamemode = <GameMode as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let hardcore = <bool as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let difficulty = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let spawn_position = <BlockCoordinates as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let achievements_disabled = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let editor_world_type = <PacketStartGameEditorWorldType as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let created_in_editor = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let exported_from_editor = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let day_cycle_stop_time = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let edu_offer = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let edu_features_enabled = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let edu_product_uuid = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let rain_level = <crate::bedrock::codec::F32LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let lightning_level = <crate::bedrock::codec::F32LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let has_confirmed_platform_locked_content = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let is_multiplayer = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let broadcast_to_lan = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let xbox_live_broadcast_mode = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let platform_broadcast_mode = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let enable_commands = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let is_texturepacks_required = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let gamerules = {
            let res: GameRules = {
                let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                        buf,
                        (),
                    )?
                    .0 as i64;
                if raw < 0 {
                    return Err(
                        std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            "array length cannot be negative",
                        ),
                    );
                }
                let len = raw as usize;
                let mut tmp_vec = Vec::with_capacity(len);
                for _ in 0..len {
                    tmp_vec
                        .push(
                            <GameRule as crate::bedrock::codec::BedrockCodec>::decode(
                                buf,
                                (),
                            )?,
                        );
                }
                tmp_vec
            };
            res
        };
        let experiments = {
            let res: Experiments = {
                let raw = <crate::bedrock::codec::I32LE as crate::bedrock::codec::BedrockCodec>::decode(
                        buf,
                        (),
                    )?
                    .0 as i64;
                if raw < 0 {
                    return Err(
                        std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            "array length cannot be negative",
                        ),
                    );
                }
                let len = raw as usize;
                let mut tmp_vec = Vec::with_capacity(len);
                for _ in 0..len {
                    tmp_vec
                        .push(
                            <Experiment as crate::bedrock::codec::BedrockCodec>::decode(
                                buf,
                                (),
                            )?,
                        );
                }
                tmp_vec
            };
            res
        };
        let experiments_previously_used = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let bonus_chest = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let map_enabled = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let permission_level = <PermissionLevel as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let server_chunk_tick_range = <crate::bedrock::codec::I32LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let has_locked_behavior_pack = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let has_locked_resource_pack = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let is_from_locked_world_template = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let msa_gamertags_only = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let is_from_world_template = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let is_world_template_option_locked = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let only_spawn_v_1_villagers = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let persona_disabled = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let custom_skins_disabled = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let emote_chat_muted = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let game_version = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let limited_world_width = <crate::bedrock::codec::I32LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let limited_world_length = <crate::bedrock::codec::I32LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let is_new_nether = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let edu_resource_uri = <EducationSharedResourceUri as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let experimental_gameplay_override = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let chat_restriction_level = <PacketStartGameChatRestrictionLevel as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let disable_player_interactions = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let server_identifier = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let world_identifier = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let scenario_identifier = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let owner_identifier = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let level_id = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let world_name = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let premium_world_template_id = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let is_trial = <bool as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let rewind_history_size = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let server_authoritative_block_breaking = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let current_tick = <crate::bedrock::codec::I64LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let enchantment_seed = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let block_properties = {
            let res: BlockProperties = {
                let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                        buf,
                        (),
                    )?
                    .0 as i64;
                if raw < 0 {
                    return Err(
                        std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            "array length cannot be negative",
                        ),
                    );
                }
                let len = raw as usize;
                let mut tmp_vec = Vec::with_capacity(len);
                for _ in 0..len {
                    tmp_vec
                        .push(
                            <BlockPropertiesItem as crate::bedrock::codec::BedrockCodec>::decode(
                                buf,
                                (),
                            )?,
                        );
                }
                tmp_vec
            };
            res
        };
        let multiplayer_correlation_id = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let server_authoritative_inventory = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let engine = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let property_data = <Vec<
            u8,
        > as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let block_pallette_checksum = <crate::bedrock::codec::U64LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let world_template_id = <uuid::Uuid as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let client_side_generation = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let block_network_ids_are_hashes = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let tick_death_systems = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let server_controlled_sound = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        Ok(Self {
            entity_id,
            runtime_entity_id,
            player_gamemode,
            player_position,
            rotation,
            seed,
            biome_type,
            biome_name,
            dimension,
            generator,
            world_gamemode,
            hardcore,
            difficulty,
            spawn_position,
            achievements_disabled,
            editor_world_type,
            created_in_editor,
            exported_from_editor,
            day_cycle_stop_time,
            edu_offer,
            edu_features_enabled,
            edu_product_uuid,
            rain_level,
            lightning_level,
            has_confirmed_platform_locked_content,
            is_multiplayer,
            broadcast_to_lan,
            xbox_live_broadcast_mode,
            platform_broadcast_mode,
            enable_commands,
            is_texturepacks_required,
            gamerules,
            experiments,
            experiments_previously_used,
            bonus_chest,
            map_enabled,
            permission_level,
            server_chunk_tick_range,
            has_locked_behavior_pack,
            has_locked_resource_pack,
            is_from_locked_world_template,
            msa_gamertags_only,
            is_from_world_template,
            is_world_template_option_locked,
            only_spawn_v_1_villagers,
            persona_disabled,
            custom_skins_disabled,
            emote_chat_muted,
            game_version,
            limited_world_width,
            limited_world_length,
            is_new_nether,
            edu_resource_uri,
            experimental_gameplay_override,
            chat_restriction_level,
            disable_player_interactions,
            server_identifier,
            world_identifier,
            scenario_identifier,
            owner_identifier,
            level_id,
            world_name,
            premium_world_template_id,
            is_trial,
            rewind_history_size,
            server_authoritative_block_breaking,
            current_tick,
            enchantment_seed,
            block_properties,
            multiplayer_correlation_id,
            server_authoritative_inventory,
            engine,
            property_data,
            block_pallette_checksum,
            world_template_id,
            client_side_generation,
            block_network_ids_are_hashes,
            tick_death_systems,
            server_controlled_sound,
        })
    }
}
