//! Generated BDS packet/runtime artifacts.
//!
//! This module is auto-generated by `unastar-data-codegen`.
//! Do not edit manually.
//!
//! Empty tables mean no validated BDS capture artifacts were present at
//! codegen time. These packet facts are intentionally separate from
//! behavior-pack gameplay semantics.
/// `BiomeDefinitionList` entry captured from BDS packet data.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct BdsBiomePacketDefinition {
    /// Namespaced biome identifier resolved through the packet string table.
    pub identifier: &'static str,
    /// Source family for this packet fact.
    pub source: &'static str,
    /// Numeric biome ID from the packet entry.
    pub biome_id: u16,
    /// String-table index from the packet entry.
    pub name_index: i16,
    /// Packet climate temperature.
    pub temperature: f32,
    /// Packet rainfall/downfall value.
    pub downfall: f32,
}
/// Raw `AvailableEntityIdentifiers` payload captured from BDS packet data.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BdsEntityIdentifiers {
    /// Source family for this packet fact.
    pub source: &'static str,
    /// Base64-encoded NBT payload as emitted by `bds-extractor`.
    pub nbt_base64: &'static str,
}
/// BDS-captured biome packet definitions.
pub const BIOME_PACKET_DEFINITIONS: [BdsBiomePacketDefinition; 0usize] = [];
/// BDS-captured entity identifier packet payload, when a capture was available.
pub const ENTITY_IDENTIFIERS: Option<BdsEntityIdentifiers> = None;
/// Look up a BDS-captured biome packet definition by numeric biome ID.
pub fn biome_by_id(biome_id: u16) -> Option<&'static BdsBiomePacketDefinition> {
    BIOME_PACKET_DEFINITIONS
        .iter()
        .find(|biome| biome.biome_id == biome_id)
}
/// Look up a BDS-captured biome packet definition by namespaced identifier.
pub fn biome_by_identifier(identifier: &str) -> Option<&'static BdsBiomePacketDefinition> {
    BIOME_PACKET_DEFINITIONS
        .iter()
        .find(|biome| biome.identifier == identifier)
}
/// Returns true when at least one BDS packet artifact was present at codegen time.
pub fn has_bds_capture() -> bool {
    !BIOME_PACKET_DEFINITIONS.is_empty() || ENTITY_IDENTIFIERS.is_some()
}
