// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(clippy::all)]
use ::bitflags::bitflags;
use bytes::{Buf, BufMut};
use super::*;
use super::super::types::*;
use crate::bedrock::codec::BedrockCodec;
pub use crate::bedrock::protocol::v1_16_201::PacketBossEvent as PacketBossEvent;
pub use crate::bedrock::protocol::v1_16_201::PacketBossEventContent as PacketBossEventContent;
pub use crate::bedrock::protocol::v1_16_201::PacketBossEventContentRegisterPlayer as PacketBossEventContentRegisterPlayer;
pub use crate::bedrock::protocol::v1_16_201::PacketBossEventContentSetBarProgress as PacketBossEventContentSetBarProgress;
pub use crate::bedrock::protocol::v1_16_201::PacketBossEventContentSetBarTitle as PacketBossEventContentSetBarTitle;
pub use crate::bedrock::protocol::v1_16_201::PacketBossEventContentShowBar as PacketBossEventContentShowBar;
pub use crate::bedrock::protocol::v1_16_201::PacketBossEventContentTexture as PacketBossEventContentTexture;
pub use crate::bedrock::protocol::v1_16_201::PacketBossEventContentUpdateProperties as PacketBossEventContentUpdateProperties;
pub use crate::bedrock::protocol::v1_16_201::PacketBossEventType as PacketBossEventType;
