// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(clippy::all)]
use ::bitflags::bitflags;
use bytes::{Buf, BufMut};
use super::*;
use super::super::types::*;
use crate::bedrock::codec::BedrockCodec;
#[derive(Debug, Clone, PartialEq)]
pub struct PacketCreativeContentItemsItem {
    pub entry_id: i32,
    pub item: ItemLegacy,
}
#[derive(Debug, Clone)]
pub struct PacketCreativeContentItemsItemArgs {
    pub shield_item_id: i32,
}
impl<'a> From<&'a crate::bedrock::context::BedrockSession>
for PacketCreativeContentItemsItemArgs {
    fn from(source: &'a crate::bedrock::context::BedrockSession) -> Self {
        Self {
            shield_item_id: source.shield_item_id,
        }
    }
}
impl crate::bedrock::codec::BedrockCodec for PacketCreativeContentItemsItem {
    type Args = PacketCreativeContentItemsItemArgs;
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        crate::bedrock::codec::VarInt(self.entry_id).encode(buf)?;
        self.item.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let entry_id = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let item = <ItemLegacy as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            ItemLegacyArgs {
                shield_item_id: args.shield_item_id,
            },
        )?;
        Ok(Self { entry_id, item })
    }
}
#[derive(Debug, Clone, PartialEq)]
pub struct PacketCreativeContent {
    pub items: Vec<PacketCreativeContentItemsItem>,
}
#[derive(Debug, Clone)]
pub struct PacketCreativeContentArgs {
    pub shield_item_id: i32,
}
impl<'a> From<&'a crate::bedrock::context::BedrockSession>
for PacketCreativeContentArgs {
    fn from(source: &'a crate::bedrock::context::BedrockSession) -> Self {
        Self {
            shield_item_id: source.shield_item_id,
        }
    }
}
impl crate::bedrock::codec::BedrockCodec for PacketCreativeContent {
    type Args = PacketCreativeContentArgs;
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        let len = self.items.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        for item in &self.items {
            item.encode(buf)?;
        }
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let items = {
            let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0 as i64;
            if raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "array length cannot be negative",
                    ),
                );
            }
            let len = raw as usize;
            let mut tmp_vec = Vec::with_capacity(len);
            for _ in 0..len {
                tmp_vec
                    .push(
                        <PacketCreativeContentItemsItem as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            PacketCreativeContentItemsItemArgs {
                                shield_item_id: args.shield_item_id,
                            },
                        )?,
                    );
            }
            tmp_vec
        };
        Ok(Self { items })
    }
}
