//! Generated definition for entity.
#[allow(unused_imports)]
use super::super::components::*;
use bevy_ecs::prelude::{Bundle, Commands, Entity};
/// Entity definition for `minecraft:bogged`
pub struct Bogged;
impl Bogged {
    /// The entity identifier
    pub const IDENTIFIER: &'static str = "minecraft:bogged";
    /// Whether this entity can spawn naturally
    pub const IS_SPAWNABLE: bool = true;
    /// Whether this entity can be summoned via commands
    pub const IS_SUMMONABLE: bool = true;
}
/// Component bundle for spawning a `minecraft:bogged`
#[derive(Bundle, Clone)]
pub struct BoggedBundle {
    pub behavior_avoid_mob_type: super::super::components::BehaviorAvoidMobType,
    pub behavior_equip_item: super::super::components::BehaviorEquipItem,
    pub behavior_flee_sun: super::super::components::BehaviorFleeSun,
    pub behavior_hurt_by_target: super::super::components::BehaviorHurtByTarget,
    pub behavior_look_at_player: super::super::components::BehaviorLookAtPlayer,
    pub behavior_nearest_attackable_target:
        super::super::components::BehaviorNearestAttackableTarget,
    pub behavior_pickup_items: super::super::components::BehaviorPickupItems,
    pub behavior_random_look_around: super::super::components::BehaviorRandomLookAround,
    pub behavior_random_stroll: super::super::components::BehaviorRandomStroll,
    pub breathable: super::super::components::Breathable,
    pub burns_in_daylight: super::super::components::BurnsInDaylight,
    pub can_climb: super::super::components::CanClimb,
    pub collision_box: super::super::components::CollisionBox,
    pub conditional_bandwidth_optimization:
        super::super::components::ConditionalBandwidthOptimization,
    pub despawn: super::super::components::Despawn,
    pub environment_sensor: super::super::components::EnvironmentSensor,
    pub equip_item: super::super::components::EquipItem,
    pub equipment: super::super::components::Equipment,
    pub experience_reward: super::super::components::ExperienceReward,
    pub health: super::super::components::Health,
    pub hurt_on_condition: super::super::components::HurtOnCondition,
    pub interact: super::super::components::Interact,
    pub is_hidden_when_invisible: super::super::components::IsHiddenWhenInvisible,
    pub jump_static: super::super::components::JumpStatic,
    pub loot: super::super::components::Loot,
    pub movement: super::super::components::Movement,
    pub movement_basic: super::super::components::MovementBasic,
    pub nameable: super::super::components::Nameable,
    pub navigation_walk: super::super::components::NavigationWalk,
    pub physics: super::super::components::Physics,
    pub pushable: super::super::components::Pushable,
    pub shareables: super::super::components::Shareables,
    pub type_family: super::super::components::TypeFamily,
}
/// Spawn a new `minecraft:bogged` entity with default Bedrock components
pub fn spawn_bogged(commands: &mut Commands) -> Entity {
    commands
        .spawn(BoggedBundle {
            behavior_avoid_mob_type: super::super::components::BehaviorAvoidMobType {
                avoid_mob_sound: Some("undefined".to_string()),
                avoid_target_xz: Some(16i32),
                avoid_target_y: Some(7i32),
                control_flags: Some(BehaviorAvoidMobTypeControlFlags {}),
                entity_types: Some(vec![BehaviorAvoidMobTypeEntityTypes {
                    check_if_outnumbered: None,
                    cooldown: None,
                    filters: Some(crate::types::BedrockValue::Object(
                        std::collections::HashMap::from([
                            (
                                "subject".to_string(),
                                crate::types::BedrockValue::String("other".to_string()),
                            ),
                            (
                                "test".to_string(),
                                crate::types::BedrockValue::String("is_family".to_string()),
                            ),
                            (
                                "value".to_string(),
                                crate::types::BedrockValue::String("wolf".to_string()),
                            ),
                        ]),
                    )),
                    max_dist: Some(6f32),
                    max_flee: None,
                    max_height: None,
                    must_see: None,
                    must_see_forget_duration: None,
                    priority: None,
                    reevaluate_description: None,
                    sprint_speed_multiplier: Some(1.2f32),
                    walk_speed_multiplier: Some(1.2f32),
                    within_default: None,
                }]),
                ignore_visibility: Some(false),
                ignore_visibilty: None,
                max_dist: Some(3f32),
                max_flee: Some(10f32),
                on_escape_event: Some(crate::types::BedrockValue::Object(
                    std::collections::HashMap::from([
                        (
                            "event".to_string(),
                            crate::types::BedrockValue::String("".to_string()),
                        ),
                        (
                            "filters".to_string(),
                            crate::types::BedrockValue::Object(std::collections::HashMap::from([
                                ("AND".to_string(), crate::types::BedrockValue::Null),
                                ("NOT".to_string(), crate::types::BedrockValue::Null),
                                ("OR".to_string(), crate::types::BedrockValue::Null),
                                ("all".to_string(), crate::types::BedrockValue::Null),
                                ("all_of".to_string(), crate::types::BedrockValue::Null),
                                ("any".to_string(), crate::types::BedrockValue::Null),
                                ("any_of".to_string(), crate::types::BedrockValue::Null),
                                ("none_of".to_string(), crate::types::BedrockValue::Null),
                            ])),
                        ),
                        (
                            "target".to_string(),
                            crate::types::BedrockValue::String("self".to_string()),
                        ),
                    ]),
                )),
                priority: Some(BehaviorAvoidMobTypePriority {}),
                probability_per_strength: Some(1f32),
                remove_target: Some(false),
                sound_interval: Some(crate::types::RangeOrVal::Range {
                    min: 3f32,
                    max: 8f32,
                }),
                sprint_distance: Some(7f32),
                sprint_speed_multiplier: Some(1f32),
                walk_speed_multiplier: Some(1f32),
            },
            behavior_equip_item: super::super::components::BehaviorEquipItem {
                priority: Some(BehaviorEquipItemPriority {}),
            },
            behavior_flee_sun: super::super::components::BehaviorFleeSun {
                priority: Some(BehaviorFleeSunPriority {}),
                speed_multiplier: Some(BehaviorFleeSunSpeedMultiplier {}),
            },
            behavior_hurt_by_target: super::super::components::BehaviorHurtByTarget {
                alert_same_type: Some(false),
                entity_types: Some(vec![BehaviorHurtByTargetEntityTypes {
                    check_if_outnumbered: None,
                    cooldown: None,
                    filters: Some(crate::types::BedrockValue::Object(
                        std::collections::HashMap::from([
                            (
                                "operator".to_string(),
                                crate::types::BedrockValue::String("!=".to_string()),
                            ),
                            (
                                "subject".to_string(),
                                crate::types::BedrockValue::String("other".to_string()),
                            ),
                            (
                                "test".to_string(),
                                crate::types::BedrockValue::String("is_family".to_string()),
                            ),
                            (
                                "value".to_string(),
                                crate::types::BedrockValue::String("breeze".to_string()),
                            ),
                        ]),
                    )),
                    max_dist: None,
                    max_flee: None,
                    max_height: None,
                    must_see: None,
                    must_see_forget_duration: None,
                    priority: None,
                    reevaluate_description: None,
                    sprint_speed_multiplier: None,
                    walk_speed_multiplier: None,
                    within_default: None,
                }]),
                hurt_owner: Some(false),
                priority: Some(BehaviorHurtByTargetPriority {}),
            },
            behavior_look_at_player: super::super::components::BehaviorLookAtPlayer {
                angle_of_view_horizontal: Some(360i32),
                angle_of_view_vertical: Some(360i32),
                look_distance: Some(8f32),
                look_time: None,
                priority: Some(BehaviorLookAtPlayerPriority {}),
                probability: Some(0.02f32),
                target_distance: None,
            },
            behavior_nearest_attackable_target:
                super::super::components::BehaviorNearestAttackableTarget {
                    attack_interval: Some(crate::types::BedrockValue::Object(
                        std::collections::HashMap::from([
                            ("max".to_string(), crate::types::BedrockValue::Integer(0i64)),
                            ("min".to_string(), crate::types::BedrockValue::Integer(0i64)),
                        ]),
                    )),
                    attack_interval_min: None,
                    attack_owner: Some(false),
                    control_flags: Some(BehaviorNearestAttackableTargetControlFlags {}),
                    entity_types: Some(vec![
                        BehaviorNearestAttackableTargetEntityTypes {
                            check_if_outnumbered: None,
                            cooldown: None,
                            filters: Some(crate::types::BedrockValue::Object(
                                std::collections::HashMap::from([
                                    (
                                        "subject".to_string(),
                                        crate::types::BedrockValue::String("other".to_string()),
                                    ),
                                    (
                                        "test".to_string(),
                                        crate::types::BedrockValue::String("is_family".to_string()),
                                    ),
                                    (
                                        "value".to_string(),
                                        crate::types::BedrockValue::String("player".to_string()),
                                    ),
                                ]),
                            )),
                            max_dist: Some(16f32),
                            max_flee: None,
                            max_height: None,
                            must_see: None,
                            must_see_forget_duration: None,
                            priority: None,
                            reevaluate_description: None,
                            sprint_speed_multiplier: None,
                            walk_speed_multiplier: None,
                            within_default: None,
                        },
                        BehaviorNearestAttackableTargetEntityTypes {
                            check_if_outnumbered: None,
                            cooldown: None,
                            filters: Some(crate::types::BedrockValue::Object(
                                std::collections::HashMap::from([
                                    (
                                        "subject".to_string(),
                                        crate::types::BedrockValue::String("other".to_string()),
                                    ),
                                    (
                                        "test".to_string(),
                                        crate::types::BedrockValue::String("is_family".to_string()),
                                    ),
                                    (
                                        "value".to_string(),
                                        crate::types::BedrockValue::String("irongolem".to_string()),
                                    ),
                                ]),
                            )),
                            max_dist: Some(16f32),
                            max_flee: None,
                            max_height: None,
                            must_see: None,
                            must_see_forget_duration: None,
                            priority: None,
                            reevaluate_description: None,
                            sprint_speed_multiplier: None,
                            walk_speed_multiplier: None,
                            within_default: None,
                        },
                        BehaviorNearestAttackableTargetEntityTypes {
                            check_if_outnumbered: None,
                            cooldown: None,
                            filters: Some(crate::types::BedrockValue::Object(
                                std::collections::HashMap::from([(
                                    "all_of".to_string(),
                                    crate::types::BedrockValue::Array(vec![
                                        crate::types::BedrockValue::Object(
                                            std::collections::HashMap::from([
                                                (
                                                    "subject".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "other".to_string(),
                                                    ),
                                                ),
                                                (
                                                    "test".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "is_family".to_string(),
                                                    ),
                                                ),
                                                (
                                                    "value".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "baby_turtle".to_string(),
                                                    ),
                                                ),
                                            ]),
                                        ),
                                        crate::types::BedrockValue::Object(
                                            std::collections::HashMap::from([
                                                (
                                                    "operator".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "!=".to_string(),
                                                    ),
                                                ),
                                                (
                                                    "subject".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "other".to_string(),
                                                    ),
                                                ),
                                                (
                                                    "test".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "in_water".to_string(),
                                                    ),
                                                ),
                                                (
                                                    "value".to_string(),
                                                    crate::types::BedrockValue::Bool(true),
                                                ),
                                            ]),
                                        ),
                                    ]),
                                )]),
                            )),
                            max_dist: Some(16f32),
                            max_flee: None,
                            max_height: None,
                            must_see: None,
                            must_see_forget_duration: None,
                            priority: None,
                            reevaluate_description: None,
                            sprint_speed_multiplier: None,
                            walk_speed_multiplier: None,
                            within_default: None,
                        },
                    ]),
                    must_reach: Some(false),
                    must_see: Some(true),
                    must_see_forget_duration: Some(3f32),
                    persist_time: Some(0f32),
                    priority: Some(BehaviorNearestAttackableTargetPriority {}),
                    reselect_targets: Some(true),
                    scan_interval: Some(10i32),
                    set_persistent: Some(false),
                    target_acquisition_probability: Some(1f32),
                    target_invisible_multiplier: Some(0.7f32),
                    target_search_height: Some(-1f32),
                    target_sneak_visibility_multiplier: Some(0.8f32),
                    within_radius: Some(0f32),
                },
            behavior_pickup_items: super::super::components::BehaviorPickupItems {
                can_pickup_any_item: Some(true),
                can_pickup_to_hand_or_equipment: Some(true),
                cooldown_after_being_attacked: None,
                excluded_items: None,
                goal_radius: Some(2f32),
                max_dist: Some(3f32),
                pickup_based_on_chance: Some(true),
                pickup_same_items_as_in_hand: None,
                priority: Some(BehaviorPickupItemsPriority {}),
                search_height: None,
                speed_multiplier: Some(BehaviorPickupItemsSpeedMultiplier {}),
                track_target: Some(false),
            },
            behavior_random_look_around: super::super::components::BehaviorRandomLookAround {
                angle_of_view_horizontal: None,
                angle_of_view_vertical: None,
                look_distance: None,
                look_time: None,
                priority: Some(BehaviorRandomLookAroundPriority {}),
                probability: None,
            },
            behavior_random_stroll: super::super::components::BehaviorRandomStroll {
                interval: Some(120i32),
                priority: Some(BehaviorRandomStrollPriority {}),
                speed_multiplier: Some(BehaviorRandomStrollSpeedMultiplier {}),
                xz_dist: Some(10i32),
                y_dist: Some(7i32),
            },
            breathable: super::super::components::Breathable {
                breathe_blocks: None,
                breathes_air: Some(true),
                breathes_lava: Some(false),
                breathes_solids: Some(false),
                breathes_water: Some(true),
                can_dehydrate: Some(false),
                generates_bubbles: Some(true),
                inhale_time: Some(0f32),
                non_breathe_blocks: None,
                suffocate_time: Some(0i32),
                total_supply: Some(15i32),
            },
            burns_in_daylight: super::super::components::BurnsInDaylight {
                value: crate::types::BedrockValue::Null,
            },
            can_climb: super::super::components::CanClimb,
            collision_box: super::super::components::CollisionBox {
                height: Some(1.9f32),
                width: Some(0.6f32),
            },
            conditional_bandwidth_optimization:
                super::super::components::ConditionalBandwidthOptimization {
                    conditional_values: None,
                    default_values: None,
                },
            despawn: super::super::components::Despawn {
                despawn_from_chance: Some(true),
                despawn_from_distance: Some(DespawnDespawnFromDistance {
                    max_distance: None,
                    min_distance: None,
                }),
                despawn_from_inactivity: Some(true),
                despawn_from_simulation_edge: Some(true),
                filters: None,
                min_range_inactivity_timer: Some(30i32),
                min_range_random_chance: Some(800i32),
                remove_child_entities: Some(false),
            },
            environment_sensor: super::super::components::EnvironmentSensor {
                triggers: Some(crate::types::BedrockValue::Array(vec![
                    crate::types::BedrockValue::Object(std::collections::HashMap::from([
                        (
                            "event".to_string(),
                            crate::types::BedrockValue::String("minecraft:melee_mode".to_string()),
                        ),
                        (
                            "filters".to_string(),
                            crate::types::BedrockValue::Object(std::collections::HashMap::from([
                                (
                                    "operator".to_string(),
                                    crate::types::BedrockValue::String("==".to_string()),
                                ),
                                (
                                    "subject".to_string(),
                                    crate::types::BedrockValue::String("self".to_string()),
                                ),
                                (
                                    "test".to_string(),
                                    crate::types::BedrockValue::String("is_underwater".to_string()),
                                ),
                                ("value".to_string(), crate::types::BedrockValue::Bool(true)),
                            ])),
                        ),
                    ])),
                    crate::types::BedrockValue::Object(std::collections::HashMap::from([
                        (
                            "event".to_string(),
                            crate::types::BedrockValue::String("minecraft:melee_mode".to_string()),
                        ),
                        (
                            "filters".to_string(),
                            crate::types::BedrockValue::Object(std::collections::HashMap::from([
                                (
                                    "operator".to_string(),
                                    crate::types::BedrockValue::String("==".to_string()),
                                ),
                                (
                                    "subject".to_string(),
                                    crate::types::BedrockValue::String("self".to_string()),
                                ),
                                (
                                    "test".to_string(),
                                    crate::types::BedrockValue::String(
                                        "has_ranged_weapon".to_string(),
                                    ),
                                ),
                                ("value".to_string(), crate::types::BedrockValue::Bool(false)),
                            ])),
                        ),
                    ])),
                ])),
            },
            equip_item: super::super::components::EquipItem {
                can_wear_armor: None,
                excluded_items: Some(vec![crate::types::BedrockValue::Object(
                    std::collections::HashMap::from([(
                        "item".to_string(),
                        crate::types::BedrockValue::String("minecraft:banner:15".to_string()),
                    )]),
                )]),
            },
            equipment: super::super::components::Equipment {
                slot_drop_chance: None,
                table: Some("loot_tables/entities/skeleton_gear.json".to_string()),
            },
            experience_reward: super::super::components::ExperienceReward {
                on_bred: Some(crate::types::MolangOr::Value(0f32)),
                on_death: Some(crate::types::MolangOr::Expr(
                    "query.last_hit_by_player ? 5 + (query.equipment_count * Math.Random(1,3)) : 0"
                        .to_string(),
                )),
            },
            health: super::super::components::Health {
                max: Some(16f32),
                min: None,
                value: crate::types::RangeOrVal::Fixed(16f32),
            },
            hurt_on_condition: super::super::components::HurtOnCondition {
                damage_conditions: None,
            },
            interact: super::super::components::Interact {
                interactions: Some(vec![InteractInteractions {
                    add_items: None,
                    admire: None,
                    barter: None,
                    cooldown: None,
                    cooldown_after_being_attacked: None,
                    drop_item_slot: None,
                    drop_item_y_offset: None,
                    equip_item_slot: None,
                    give_item: None,
                    health_amount: None,
                    hurt_item: Some(1i32),
                    interact_text: Some("action.interact.shear".to_string()),
                    on_interact: Some(crate::types::BedrockValue::Object(
                        std::collections::HashMap::from([
                            (
                                "event".to_string(),
                                crate::types::BedrockValue::String("be_sheared".to_string()),
                            ),
                            (
                                "filters".to_string(),
                                crate::types::BedrockValue::Object(
                                    std::collections::HashMap::from([(
                                        "all_of".to_string(),
                                        crate::types::BedrockValue::Array(vec![
                                            crate::types::BedrockValue::Object(
                                                std::collections::HashMap::from([
                                                    (
                                                        "domain".to_string(),
                                                        crate::types::BedrockValue::String(
                                                            "hand".to_string(),
                                                        ),
                                                    ),
                                                    (
                                                        "subject".to_string(),
                                                        crate::types::BedrockValue::String(
                                                            "other".to_string(),
                                                        ),
                                                    ),
                                                    (
                                                        "test".to_string(),
                                                        crate::types::BedrockValue::String(
                                                            "has_equipment".to_string(),
                                                        ),
                                                    ),
                                                    (
                                                        "value".to_string(),
                                                        crate::types::BedrockValue::String(
                                                            "shears".to_string(),
                                                        ),
                                                    ),
                                                ]),
                                            ),
                                            crate::types::BedrockValue::Object(
                                                std::collections::HashMap::from([
                                                    (
                                                        "operator".to_string(),
                                                        crate::types::BedrockValue::String(
                                                            "!=".to_string(),
                                                        ),
                                                    ),
                                                    (
                                                        "test".to_string(),
                                                        crate::types::BedrockValue::String(
                                                            "has_component".to_string(),
                                                        ),
                                                    ),
                                                    (
                                                        "value".to_string(),
                                                        crate::types::BedrockValue::String(
                                                            "minecraft:is_sheared".to_string(),
                                                        ),
                                                    ),
                                                ]),
                                            ),
                                        ]),
                                    )]),
                                ),
                            ),
                            (
                                "target".to_string(),
                                crate::types::BedrockValue::String("self".to_string()),
                            ),
                        ]),
                    )),
                    particle_on_start: None,
                    play_sounds: Some("shear".to_string()),
                    repair_entity_item: None,
                    spawn_entities: None,
                    spawn_items: Some(InteractInteractionsSpawnItems {
                        table: Some("loot_tables/entities/bogged_shear.json".to_string()),
                        y_offset: None,
                    }),
                    swing: None,
                    take_item: None,
                    transform_to_item: None,
                    use_item: Some(false),
                    vibration: None,
                }]),
            },
            is_hidden_when_invisible: super::super::components::IsHiddenWhenInvisible,
            jump_static: super::super::components::JumpStatic {
                jump_power: Some(0.42f32),
            },
            loot: super::super::components::Loot {
                table: "loot_tables/entities/bogged.json".to_string(),
            },
            movement: super::super::components::Movement {
                max: None,
                min: None,
                value: crate::types::RangeOrVal::Fixed(0.25f32),
            },
            movement_basic: super::super::components::MovementBasic {
                max_turn: Some(30f32),
            },
            nameable: super::super::components::Nameable {
                allow_name_tag_renaming: Some(true),
                always_show: Some(false),
                default_trigger: None,
                name_actions: None,
            },
            navigation_walk: super::super::components::NavigationWalk {
                avoid_damage_blocks: Some(false),
                avoid_portals: Some(false),
                avoid_sun: Some(true),
                avoid_water: Some(true),
                blocks_to_avoid: None,
                can_breach: Some(false),
                can_break_doors: Some(false),
                can_float: None,
                can_jump: Some(true),
                can_open_doors: Some(false),
                can_open_iron_doors: Some(false),
                can_pass_doors: Some(true),
                can_path_from_air: Some(false),
                can_path_over_lava: Some(false),
                can_path_over_water: Some(false),
                can_sink: Some(true),
                can_swim: Some(false),
                can_walk: Some(true),
                can_walk_in_lava: Some(false),
                is_amphibious: Some(true),
            },
            physics: super::super::components::Physics {
                has_collision: Some(true),
                has_gravity: Some(true),
                push_towards_closest_space: Some(false),
            },
            pushable: super::super::components::Pushable {
                is_pushable: Some(true),
                is_pushable_by_piston: Some(true),
            },
            shareables: super::super::components::Shareables {
                all_items: Some(false),
                all_items_max_amount: Some(-1i32),
                all_items_surplus_amount: Some(-1i32),
                all_items_want_amount: Some(-1i32),
                items: Some(vec![
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:stone_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:wooden_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:bow".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:turtle_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(7i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:0".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:1".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:carved_pumpkin".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                ]),
                singular_pickup: Some(true),
            },
            type_family: super::super::components::TypeFamily {
                family: vec![
                    "bogged".to_string(),
                    "skeleton".to_string(),
                    "monster".to_string(),
                    "mob".to_string(),
                    "undead".to_string(),
                ],
            },
        })
        .id()
}
/// Component groups for this entity
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BoggedComponentGroup {
    BoggedSheared,
    MeleeAttack,
    RangedAttack,
}
/// Events for this entity
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum BoggedEvent {
    BeSheared,
    EntitySpawned,
    MeleeMode,
    RangedMode,
}
