//! Generated definition for entity.
#[allow(unused_imports)]
use super::super::components::*;
use bevy_ecs::prelude::{Bundle, Commands, Entity};
/// Entity definition for `minecraft:drowned`
pub struct Drowned;
impl Drowned {
    /// The entity identifier
    pub const IDENTIFIER: &'static str = "minecraft:drowned";
    /// Whether this entity can spawn naturally
    pub const IS_SPAWNABLE: bool = true;
    /// Whether this entity can be summoned via commands
    pub const IS_SUMMONABLE: bool = true;
}
/// Component bundle for spawning a `minecraft:drowned`
#[derive(Bundle, Clone)]
pub struct DrownedBundle {
    pub behavior_equip_item: super::super::components::BehaviorEquipItem,
    pub behavior_flee_sun: super::super::components::BehaviorFleeSun,
    pub behavior_hurt_by_target: super::super::components::BehaviorHurtByTarget,
    pub behavior_look_at_player: super::super::components::BehaviorLookAtPlayer,
    pub behavior_nearest_attackable_target:
        super::super::components::BehaviorNearestAttackableTarget,
    pub behavior_pickup_items: super::super::components::BehaviorPickupItems,
    pub behavior_random_look_around: super::super::components::BehaviorRandomLookAround,
    pub behavior_random_stroll: super::super::components::BehaviorRandomStroll,
    pub behavior_stomp_turtle_egg: super::super::components::BehaviorStompTurtleEgg,
    pub breathable: super::super::components::Breathable,
    pub burns_in_daylight: super::super::components::BurnsInDaylight,
    pub can_climb: super::super::components::CanClimb,
    pub collision_box: super::super::components::CollisionBox,
    pub conditional_bandwidth_optimization:
        super::super::components::ConditionalBandwidthOptimization,
    pub despawn: super::super::components::Despawn,
    pub equip_item: super::super::components::EquipItem,
    pub health: super::super::components::Health,
    pub hurt_on_condition: super::super::components::HurtOnCondition,
    pub jump_static: super::super::components::JumpStatic,
    pub movement: super::super::components::Movement,
    pub movement_generic: super::super::components::MovementGeneric,
    pub nameable: super::super::components::Nameable,
    pub navigation_generic: super::super::components::NavigationGeneric,
    pub on_target_acquired: super::super::components::OnTargetAcquired,
    pub on_target_escape: super::super::components::OnTargetEscape,
    pub physics: super::super::components::Physics,
    pub pushable: super::super::components::Pushable,
    pub rotation_locked_to_vehicle: super::super::components::RotationLockedToVehicle,
    pub shareables: super::super::components::Shareables,
    pub type_family: super::super::components::TypeFamily,
    pub underwater_movement: super::super::components::UnderwaterMovement,
}
/// Spawn a new `minecraft:drowned` entity with default Bedrock components
pub fn spawn_drowned(commands: &mut Commands) -> Entity {
    commands
        .spawn(DrownedBundle {
            behavior_equip_item: super::super::components::BehaviorEquipItem {
                priority: Some(BehaviorEquipItemPriority {}),
            },
            behavior_flee_sun: super::super::components::BehaviorFleeSun {
                priority: Some(BehaviorFleeSunPriority {}),
                speed_multiplier: Some(BehaviorFleeSunSpeedMultiplier {}),
            },
            behavior_hurt_by_target: super::super::components::BehaviorHurtByTarget {
                alert_same_type: Some(false),
                entity_types: None,
                hurt_owner: Some(false),
                priority: Some(BehaviorHurtByTargetPriority {}),
            },
            behavior_look_at_player: super::super::components::BehaviorLookAtPlayer {
                angle_of_view_horizontal: Some(360i32),
                angle_of_view_vertical: Some(360i32),
                look_distance: Some(6f32),
                look_time: None,
                priority: Some(BehaviorLookAtPlayerPriority {}),
                probability: Some(0.02f32),
                target_distance: None,
            },
            behavior_nearest_attackable_target:
                super::super::components::BehaviorNearestAttackableTarget {
                    attack_interval: Some(crate::types::BedrockValue::Object(
                        std::collections::HashMap::from([
                            ("max".to_string(), crate::types::BedrockValue::Integer(0i64)),
                            ("min".to_string(), crate::types::BedrockValue::Integer(0i64)),
                        ]),
                    )),
                    attack_interval_min: None,
                    attack_owner: Some(false),
                    control_flags: Some(BehaviorNearestAttackableTargetControlFlags {}),
                    entity_types: Some(vec![
                        BehaviorNearestAttackableTargetEntityTypes {
                            check_if_outnumbered: None,
                            cooldown: None,
                            filters: Some(crate::types::BedrockValue::Object(
                                std::collections::HashMap::from([(
                                    "all_of".to_string(),
                                    crate::types::BedrockValue::Array(vec![
                                        crate::types::BedrockValue::Object(
                                            std::collections::HashMap::from([(
                                                "any_of".to_string(),
                                                crate::types::BedrockValue::Array(vec![
                                                    crate::types::BedrockValue::Object(
                                                        std::collections::HashMap::from([
                                                            (
                                                                "subject".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "other".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "test".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "is_family".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "value".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "player".to_string(),
                                                                ),
                                                            ),
                                                        ]),
                                                    ),
                                                    crate::types::BedrockValue::Object(
                                                        std::collections::HashMap::from([
                                                            (
                                                                "subject".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "other".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "test".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "is_family".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "value".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "snowgolem".to_string(),
                                                                ),
                                                            ),
                                                        ]),
                                                    ),
                                                    crate::types::BedrockValue::Object(
                                                        std::collections::HashMap::from([
                                                            (
                                                                "subject".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "other".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "test".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "is_family".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "value".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "irongolem".to_string(),
                                                                ),
                                                            ),
                                                        ]),
                                                    ),
                                                    crate::types::BedrockValue::Object(
                                                        std::collections::HashMap::from([
                                                            (
                                                                "subject".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "other".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "test".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "is_family".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "value".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "axolotl".to_string(),
                                                                ),
                                                            ),
                                                        ]),
                                                    ),
                                                ]),
                                            )]),
                                        ),
                                        crate::types::BedrockValue::Object(
                                            std::collections::HashMap::from([(
                                                "any_of".to_string(),
                                                crate::types::BedrockValue::Array(vec![
                                                    crate::types::BedrockValue::Object(
                                                        std::collections::HashMap::from([
                                                            (
                                                                "subject".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "other".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "test".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "in_water".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "value".to_string(),
                                                                crate::types::BedrockValue::Bool(
                                                                    true,
                                                                ),
                                                            ),
                                                        ]),
                                                    ),
                                                    crate::types::BedrockValue::Object(
                                                        std::collections::HashMap::from([
                                                            (
                                                                "test".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "is_daytime".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "value".to_string(),
                                                                crate::types::BedrockValue::Bool(
                                                                    false,
                                                                ),
                                                            ),
                                                        ]),
                                                    ),
                                                ]),
                                            )]),
                                        ),
                                    ]),
                                )]),
                            )),
                            max_dist: Some(20f32),
                            max_flee: None,
                            max_height: None,
                            must_see: None,
                            must_see_forget_duration: None,
                            priority: None,
                            reevaluate_description: None,
                            sprint_speed_multiplier: None,
                            walk_speed_multiplier: None,
                            within_default: None,
                        },
                        BehaviorNearestAttackableTargetEntityTypes {
                            check_if_outnumbered: None,
                            cooldown: None,
                            filters: Some(crate::types::BedrockValue::Object(
                                std::collections::HashMap::from([(
                                    "all_of".to_string(),
                                    crate::types::BedrockValue::Array(vec![
                                        crate::types::BedrockValue::Object(
                                            std::collections::HashMap::from([(
                                                "any_of".to_string(),
                                                crate::types::BedrockValue::Array(vec![
                                                    crate::types::BedrockValue::Object(
                                                        std::collections::HashMap::from([
                                                            (
                                                                "subject".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "other".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "test".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "is_family".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "value".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "villager".to_string(),
                                                                ),
                                                            ),
                                                        ]),
                                                    ),
                                                    crate::types::BedrockValue::Object(
                                                        std::collections::HashMap::from([
                                                            (
                                                                "subject".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "other".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "test".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "is_family".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "value".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "wandering_trader".to_string(),
                                                                ),
                                                            ),
                                                        ]),
                                                    ),
                                                ]),
                                            )]),
                                        ),
                                        crate::types::BedrockValue::Object(
                                            std::collections::HashMap::from([(
                                                "any_of".to_string(),
                                                crate::types::BedrockValue::Array(vec![
                                                    crate::types::BedrockValue::Object(
                                                        std::collections::HashMap::from([
                                                            (
                                                                "subject".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "other".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "test".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "in_water".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "value".to_string(),
                                                                crate::types::BedrockValue::Bool(
                                                                    true,
                                                                ),
                                                            ),
                                                        ]),
                                                    ),
                                                    crate::types::BedrockValue::Object(
                                                        std::collections::HashMap::from([
                                                            (
                                                                "test".to_string(),
                                                                crate::types::BedrockValue::String(
                                                                    "is_daytime".to_string(),
                                                                ),
                                                            ),
                                                            (
                                                                "value".to_string(),
                                                                crate::types::BedrockValue::Bool(
                                                                    false,
                                                                ),
                                                            ),
                                                        ]),
                                                    ),
                                                ]),
                                            )]),
                                        ),
                                    ]),
                                )]),
                            )),
                            max_dist: Some(20f32),
                            max_flee: None,
                            max_height: None,
                            must_see: Some(false),
                            must_see_forget_duration: None,
                            priority: None,
                            reevaluate_description: None,
                            sprint_speed_multiplier: None,
                            walk_speed_multiplier: None,
                            within_default: None,
                        },
                        BehaviorNearestAttackableTargetEntityTypes {
                            check_if_outnumbered: None,
                            cooldown: None,
                            filters: Some(crate::types::BedrockValue::Object(
                                std::collections::HashMap::from([(
                                    "all_of".to_string(),
                                    crate::types::BedrockValue::Array(vec![
                                        crate::types::BedrockValue::Object(
                                            std::collections::HashMap::from([
                                                (
                                                    "subject".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "other".to_string(),
                                                    ),
                                                ),
                                                (
                                                    "test".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "is_family".to_string(),
                                                    ),
                                                ),
                                                (
                                                    "value".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "baby_turtle".to_string(),
                                                    ),
                                                ),
                                            ]),
                                        ),
                                        crate::types::BedrockValue::Object(
                                            std::collections::HashMap::from([
                                                (
                                                    "operator".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "!=".to_string(),
                                                    ),
                                                ),
                                                (
                                                    "subject".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "other".to_string(),
                                                    ),
                                                ),
                                                (
                                                    "test".to_string(),
                                                    crate::types::BedrockValue::String(
                                                        "in_water".to_string(),
                                                    ),
                                                ),
                                                (
                                                    "value".to_string(),
                                                    crate::types::BedrockValue::Bool(true),
                                                ),
                                            ]),
                                        ),
                                    ]),
                                )]),
                            )),
                            max_dist: Some(20f32),
                            max_flee: None,
                            max_height: None,
                            must_see: None,
                            must_see_forget_duration: None,
                            priority: None,
                            reevaluate_description: None,
                            sprint_speed_multiplier: None,
                            walk_speed_multiplier: None,
                            within_default: None,
                        },
                    ]),
                    must_reach: Some(false),
                    must_see: Some(true),
                    must_see_forget_duration: Some(17f32),
                    persist_time: Some(0.5f32),
                    priority: Some(BehaviorNearestAttackableTargetPriority {}),
                    reselect_targets: Some(true),
                    scan_interval: Some(10i32),
                    set_persistent: Some(false),
                    target_acquisition_probability: Some(1f32),
                    target_invisible_multiplier: Some(0.7f32),
                    target_search_height: Some(-1f32),
                    target_sneak_visibility_multiplier: Some(0.8f32),
                    within_radius: Some(12f32),
                },
            behavior_pickup_items: super::super::components::BehaviorPickupItems {
                can_pickup_any_item: Some(true),
                can_pickup_to_hand_or_equipment: Some(true),
                cooldown_after_being_attacked: None,
                excluded_items: Some(vec![crate::types::BedrockValue::String(
                    "minecraft:glow_ink_sac".to_string(),
                )]),
                goal_radius: Some(2f32),
                max_dist: Some(3f32),
                pickup_based_on_chance: Some(true),
                pickup_same_items_as_in_hand: None,
                priority: Some(BehaviorPickupItemsPriority {}),
                search_height: None,
                speed_multiplier: Some(BehaviorPickupItemsSpeedMultiplier {}),
                track_target: Some(false),
            },
            behavior_random_look_around: super::super::components::BehaviorRandomLookAround {
                angle_of_view_horizontal: None,
                angle_of_view_vertical: None,
                look_distance: None,
                look_time: None,
                priority: Some(BehaviorRandomLookAroundPriority {}),
                probability: None,
            },
            behavior_random_stroll: super::super::components::BehaviorRandomStroll {
                interval: Some(120i32),
                priority: Some(BehaviorRandomStrollPriority {}),
                speed_multiplier: Some(BehaviorRandomStrollSpeedMultiplier {}),
                xz_dist: Some(10i32),
                y_dist: Some(7i32),
            },
            behavior_stomp_turtle_egg: super::super::components::BehaviorStompTurtleEgg {
                goal_radius: Some(1.14f32),
                interval: Some(20i32),
                priority: Some(BehaviorStompTurtleEggPriority {}),
                search_count: None,
                search_height: Some(2i32),
                search_range: Some(10i32),
                speed_multiplier: Some(BehaviorStompTurtleEggSpeedMultiplier {}),
            },
            breathable: super::super::components::Breathable {
                breathe_blocks: None,
                breathes_air: Some(true),
                breathes_lava: Some(false),
                breathes_solids: Some(false),
                breathes_water: Some(true),
                can_dehydrate: Some(false),
                generates_bubbles: Some(true),
                inhale_time: Some(0f32),
                non_breathe_blocks: None,
                suffocate_time: Some(0i32),
                total_supply: Some(15i32),
            },
            burns_in_daylight: super::super::components::BurnsInDaylight {
                value: crate::types::BedrockValue::Null,
            },
            can_climb: super::super::components::CanClimb,
            collision_box: super::super::components::CollisionBox {
                height: Some(1.9f32),
                width: Some(0.6f32),
            },
            conditional_bandwidth_optimization:
                super::super::components::ConditionalBandwidthOptimization {
                    conditional_values: None,
                    default_values: None,
                },
            despawn: super::super::components::Despawn {
                despawn_from_chance: Some(true),
                despawn_from_distance: Some(DespawnDespawnFromDistance {
                    max_distance: None,
                    min_distance: None,
                }),
                despawn_from_inactivity: Some(true),
                despawn_from_simulation_edge: Some(true),
                filters: None,
                min_range_inactivity_timer: Some(30i32),
                min_range_random_chance: Some(800i32),
                remove_child_entities: Some(false),
            },
            equip_item: super::super::components::EquipItem {
                can_wear_armor: None,
                excluded_items: Some(vec![crate::types::BedrockValue::Object(
                    std::collections::HashMap::from([(
                        "item".to_string(),
                        crate::types::BedrockValue::String("minecraft:banner:15".to_string()),
                    )]),
                )]),
            },
            health: super::super::components::Health {
                max: Some(20f32),
                min: None,
                value: crate::types::RangeOrVal::Fixed(20f32),
            },
            hurt_on_condition: super::super::components::HurtOnCondition {
                damage_conditions: None,
            },
            jump_static: super::super::components::JumpStatic {
                jump_power: Some(0.42f32),
            },
            movement: super::super::components::Movement {
                max: None,
                min: None,
                value: crate::types::RangeOrVal::Fixed(0.23f32),
            },
            movement_generic: super::super::components::MovementGeneric {
                max_turn: Some(30f32),
            },
            nameable: super::super::components::Nameable {
                allow_name_tag_renaming: Some(true),
                always_show: Some(false),
                default_trigger: None,
                name_actions: None,
            },
            navigation_generic: super::super::components::NavigationGeneric {
                avoid_damage_blocks: Some(false),
                avoid_portals: Some(false),
                avoid_sun: Some(true),
                avoid_water: Some(false),
                blocks_to_avoid: None,
                can_breach: Some(false),
                can_break_doors: Some(true),
                can_jump: Some(true),
                can_open_doors: Some(false),
                can_open_iron_doors: Some(false),
                can_pass_doors: Some(true),
                can_path_from_air: Some(false),
                can_path_over_lava: Some(false),
                can_path_over_water: Some(false),
                can_sink: Some(true),
                can_swim: Some(false),
                can_walk: Some(true),
                can_walk_in_lava: Some(false),
                is_amphibious: Some(true),
            },
            on_target_acquired: super::super::components::OnTargetAcquired {
                value: crate::types::BedrockValue::Null,
            },
            on_target_escape: super::super::components::OnTargetEscape {
                value: crate::types::BedrockValue::Null,
            },
            physics: super::super::components::Physics {
                has_collision: Some(true),
                has_gravity: Some(true),
                push_towards_closest_space: Some(false),
            },
            pushable: super::super::components::Pushable {
                is_pushable: Some(true),
                is_pushable_by_piston: Some(true),
            },
            rotation_locked_to_vehicle: super::super::components::RotationLockedToVehicle,
            shareables: super::super::components::Shareables {
                all_items: Some(false),
                all_items_max_amount: Some(-1i32),
                all_items_surplus_amount: Some(-1i32),
                all_items_want_amount: Some(-1i32),
                items: Some(vec![
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:trident".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:nautilus_shell".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:stone_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(7i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:wooden_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:turtle_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(7i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:0".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:1".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:carved_pumpkin".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                ]),
                singular_pickup: Some(true),
            },
            type_family: super::super::components::TypeFamily {
                family: vec![
                    "drowned".to_string(),
                    "zombie".to_string(),
                    "undead".to_string(),
                    "monster".to_string(),
                    "mob".to_string(),
                ],
            },
            underwater_movement: super::super::components::UnderwaterMovement {
                max: None,
                min: None,
                value: crate::types::RangeOrVal::Fixed(0.06f32),
            },
        })
        .id()
}
/// Component groups for this entity
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DrownedComponentGroup {
    AdultDrowned,
    BabyDrowned,
    CanBreakDoors,
    DrownedRider,
    HunterMode,
    MeleeEquipment,
    MeleeMode,
    ModeSwitcher,
    RangedEquipment,
    RangedMode,
    WanderMode,
}
/// Events for this entity
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DrownedEvent {
    AsAdult,
    AsBaby,
    AsRangedAdult,
    AsRider,
    EntitySpawned,
    HasTarget,
    LostTarget,
    SwitchToMelee,
    SwitchToRanged,
}
