//! Generated definition for entity.
#[allow(unused_imports)]
use super::super::components::*;
use bevy_ecs::prelude::{Bundle, Commands, Entity};
/// Entity definition for `minecraft:piglin`
pub struct Piglin;
impl Piglin {
    /// The entity identifier
    pub const IDENTIFIER: &'static str = "minecraft:piglin";
    /// Whether this entity can spawn naturally
    pub const IS_SPAWNABLE: bool = true;
    /// Whether this entity can be summoned via commands
    pub const IS_SUMMONABLE: bool = true;
}
/// Component bundle for spawning a `minecraft:piglin`
#[derive(Bundle, Clone)]
pub struct PiglinBundle {
    pub admire_item: super::super::components::AdmireItem,
    pub annotation_open_door: super::super::components::AnnotationOpenDoor,
    pub behavior_admire_item: super::super::components::BehaviorAdmireItem,
    pub behavior_avoid_block: super::super::components::BehaviorAvoidBlock,
    pub behavior_avoid_mob_type: super::super::components::BehaviorAvoidMobType,
    pub behavior_barter: super::super::components::BehaviorBarter,
    pub behavior_equip_item: super::super::components::BehaviorEquipItem,
    pub behavior_hurt_by_target: super::super::components::BehaviorHurtByTarget,
    pub behavior_look_at_player: super::super::components::BehaviorLookAtPlayer,
    pub behavior_pickup_items: super::super::components::BehaviorPickupItems,
    pub behavior_random_look_around: super::super::components::BehaviorRandomLookAround,
    pub behavior_random_stroll: super::super::components::BehaviorRandomStroll,
    pub breathable: super::super::components::Breathable,
    pub collision_box: super::super::components::CollisionBox,
    pub conditional_bandwidth_optimization:
        super::super::components::ConditionalBandwidthOptimization,
    pub despawn: super::super::components::Despawn,
    pub equip_item: super::super::components::EquipItem,
    pub follow_range: super::super::components::FollowRange,
    pub health: super::super::components::Health,
    pub hurt_on_condition: super::super::components::HurtOnCondition,
    pub inventory: super::super::components::Inventory,
    pub is_hidden_when_invisible: super::super::components::IsHiddenWhenInvisible,
    pub jump_static: super::super::components::JumpStatic,
    pub loot: super::super::components::Loot,
    pub movement_basic: super::super::components::MovementBasic,
    pub nameable: super::super::components::Nameable,
    pub navigation_walk: super::super::components::NavigationWalk,
    pub on_target_acquired: super::super::components::OnTargetAcquired,
    pub physics: super::super::components::Physics,
    pub pushable: super::super::components::Pushable,
    pub shareables: super::super::components::Shareables,
}
/// Spawn a new `minecraft:piglin` entity with default Bedrock components
pub fn spawn_piglin(commands: &mut Commands) -> Entity {
    commands
        .spawn(PiglinBundle {
            admire_item: super::super::components::AdmireItem {
                cooldown_after_being_attacked: Some(20i32),
                duration: Some(8i32),
            },
            annotation_open_door: super::super::components::AnnotationOpenDoor,
            behavior_admire_item: super::super::components::BehaviorAdmireItem {
                admire_item_sound: Some("admire".to_string()),
                on_admire_item_start: Some(crate::types::BedrockValue::Object(
                    std::collections::HashMap::from([
                        (
                            "event".to_string(),
                            crate::types::BedrockValue::String(
                                "admire_item_started_event".to_string(),
                            ),
                        ),
                        (
                            "target".to_string(),
                            crate::types::BedrockValue::String("self".to_string()),
                        ),
                    ]),
                )),
                on_admire_item_stop: Some(crate::types::BedrockValue::Object(
                    std::collections::HashMap::from([
                        (
                            "event".to_string(),
                            crate::types::BedrockValue::String(
                                "admire_item_stopped_event".to_string(),
                            ),
                        ),
                        (
                            "target".to_string(),
                            crate::types::BedrockValue::String("self".to_string()),
                        ),
                    ]),
                )),
                priority: Some(BehaviorAdmireItemPriority {}),
                sound_interval: Some(crate::types::RangeOrVal::Range {
                    min: 8f32,
                    max: 8f32,
                }),
            },
            behavior_avoid_block: super::super::components::BehaviorAvoidBlock {
                avoid_block_sound: Some("retreat".to_string()),
                control_flags: Some(BehaviorAvoidBlockControlFlags {}),
                on_escape: Some(vec![]),
                priority: Some(BehaviorAvoidBlockPriority {}),
                search_height: Some(4i32),
                search_range: Some(8i32),
                sound_interval: Some(crate::types::RangeOrVal::Range {
                    min: 2f32,
                    max: 5f32,
                }),
                sprint_speed_modifier: Some(1.1f32),
                target_blocks: Some(vec![
                    crate::types::BedrockValue::String("minecraft:soul_fire".to_string()),
                    crate::types::BedrockValue::String("minecraft:soul_lantern".to_string()),
                    crate::types::BedrockValue::String("minecraft:soul_torch".to_string()),
                    crate::types::BedrockValue::String("minecraft:item.soul_campfire".to_string()),
                ]),
                target_selection_method: Some("nearest".to_string()),
                tick_interval: Some(5i32),
                walk_speed_modifier: Some(1f32),
            },
            behavior_avoid_mob_type: super::super::components::BehaviorAvoidMobType {
                avoid_mob_sound: Some("retreat".to_string()),
                avoid_target_xz: Some(16i32),
                avoid_target_y: Some(7i32),
                control_flags: Some(BehaviorAvoidMobTypeControlFlags {}),
                entity_types: Some(vec![
                    BehaviorAvoidMobTypeEntityTypes {
                        check_if_outnumbered: None,
                        cooldown: None,
                        filters: Some(crate::types::BedrockValue::Object(
                            std::collections::HashMap::from([(
                                "any_of".to_string(),
                                crate::types::BedrockValue::Array(vec![
                                    crate::types::BedrockValue::Object(
                                        std::collections::HashMap::from([
                                            (
                                                "subject".to_string(),
                                                crate::types::BedrockValue::String(
                                                    "other".to_string(),
                                                ),
                                            ),
                                            (
                                                "test".to_string(),
                                                crate::types::BedrockValue::String(
                                                    "is_family".to_string(),
                                                ),
                                            ),
                                            (
                                                "value".to_string(),
                                                crate::types::BedrockValue::String(
                                                    "zombie_pigman".to_string(),
                                                ),
                                            ),
                                        ]),
                                    ),
                                ]),
                            )]),
                        )),
                        max_dist: Some(6f32),
                        max_flee: None,
                        max_height: None,
                        must_see: None,
                        must_see_forget_duration: None,
                        priority: None,
                        reevaluate_description: None,
                        sprint_speed_multiplier: None,
                        walk_speed_multiplier: None,
                        within_default: None,
                    },
                    BehaviorAvoidMobTypeEntityTypes {
                        check_if_outnumbered: None,
                        cooldown: None,
                        filters: Some(crate::types::BedrockValue::Object(
                            std::collections::HashMap::from([(
                                "any_of".to_string(),
                                crate::types::BedrockValue::Array(vec![
                                    crate::types::BedrockValue::Object(
                                        std::collections::HashMap::from([
                                            (
                                                "subject".to_string(),
                                                crate::types::BedrockValue::String(
                                                    "other".to_string(),
                                                ),
                                            ),
                                            (
                                                "test".to_string(),
                                                crate::types::BedrockValue::String(
                                                    "is_family".to_string(),
                                                ),
                                            ),
                                            (
                                                "value".to_string(),
                                                crate::types::BedrockValue::String(
                                                    "zoglin".to_string(),
                                                ),
                                            ),
                                        ]),
                                    ),
                                ]),
                            )]),
                        )),
                        max_dist: Some(6f32),
                        max_flee: None,
                        max_height: None,
                        must_see: None,
                        must_see_forget_duration: None,
                        priority: None,
                        reevaluate_description: None,
                        sprint_speed_multiplier: None,
                        walk_speed_multiplier: None,
                        within_default: None,
                    },
                    BehaviorAvoidMobTypeEntityTypes {
                        check_if_outnumbered: Some(true),
                        cooldown: None,
                        filters: Some(crate::types::BedrockValue::Object(
                            std::collections::HashMap::from([(
                                "all_of".to_string(),
                                crate::types::BedrockValue::Array(vec![
                                    crate::types::BedrockValue::Object(
                                        std::collections::HashMap::from([
                                            (
                                                "subject".to_string(),
                                                crate::types::BedrockValue::String(
                                                    "other".to_string(),
                                                ),
                                            ),
                                            (
                                                "test".to_string(),
                                                crate::types::BedrockValue::String(
                                                    "has_target".to_string(),
                                                ),
                                            ),
                                        ]),
                                    ),
                                    crate::types::BedrockValue::Object(
                                        std::collections::HashMap::from([
                                            (
                                                "subject".to_string(),
                                                crate::types::BedrockValue::String(
                                                    "other".to_string(),
                                                ),
                                            ),
                                            (
                                                "test".to_string(),
                                                crate::types::BedrockValue::String(
                                                    "is_family".to_string(),
                                                ),
                                            ),
                                            (
                                                "value".to_string(),
                                                crate::types::BedrockValue::String(
                                                    "hoglin".to_string(),
                                                ),
                                            ),
                                        ]),
                                    ),
                                ]),
                            )]),
                        )),
                        max_dist: None,
                        max_flee: None,
                        max_height: None,
                        must_see: None,
                        must_see_forget_duration: None,
                        priority: None,
                        reevaluate_description: None,
                        sprint_speed_multiplier: Some(1.2f32),
                        walk_speed_multiplier: None,
                        within_default: None,
                    },
                ]),
                ignore_visibility: Some(false),
                ignore_visibilty: None,
                max_dist: Some(3f32),
                max_flee: Some(10f32),
                on_escape_event: Some(crate::types::BedrockValue::Object(
                    std::collections::HashMap::from([
                        (
                            "event".to_string(),
                            crate::types::BedrockValue::String("become_calm_event".to_string()),
                        ),
                        (
                            "target".to_string(),
                            crate::types::BedrockValue::String("self".to_string()),
                        ),
                    ]),
                )),
                priority: Some(BehaviorAvoidMobTypePriority {}),
                probability_per_strength: Some(1f32),
                remove_target: Some(true),
                sound_interval: Some(crate::types::RangeOrVal::Range {
                    min: 2f32,
                    max: 5f32,
                }),
                sprint_distance: Some(7f32),
                sprint_speed_multiplier: Some(1f32),
                walk_speed_multiplier: Some(1f32),
            },
            behavior_barter: super::super::components::BehaviorBarter {
                priority: Some(BehaviorBarterPriority {}),
            },
            behavior_equip_item: super::super::components::BehaviorEquipItem {
                priority: Some(BehaviorEquipItemPriority {}),
            },
            behavior_hurt_by_target: super::super::components::BehaviorHurtByTarget {
                alert_same_type: Some(false),
                entity_types: None,
                hurt_owner: Some(false),
                priority: Some(BehaviorHurtByTargetPriority {}),
            },
            behavior_look_at_player: super::super::components::BehaviorLookAtPlayer {
                angle_of_view_horizontal: Some(360i32),
                angle_of_view_vertical: Some(360i32),
                look_distance: Some(8f32),
                look_time: None,
                priority: Some(BehaviorLookAtPlayerPriority {}),
                probability: Some(0.02f32),
                target_distance: None,
            },
            behavior_pickup_items: super::super::components::BehaviorPickupItems {
                can_pickup_any_item: Some(false),
                can_pickup_to_hand_or_equipment: Some(true),
                cooldown_after_being_attacked: Some(20f32),
                excluded_items: None,
                goal_radius: Some(2f32),
                max_dist: Some(10f32),
                pickup_based_on_chance: Some(false),
                pickup_same_items_as_in_hand: None,
                priority: Some(BehaviorPickupItemsPriority {}),
                search_height: None,
                speed_multiplier: Some(BehaviorPickupItemsSpeedMultiplier {}),
                track_target: Some(false),
            },
            behavior_random_look_around: super::super::components::BehaviorRandomLookAround {
                angle_of_view_horizontal: None,
                angle_of_view_vertical: None,
                look_distance: None,
                look_time: None,
                priority: Some(BehaviorRandomLookAroundPriority {}),
                probability: None,
            },
            behavior_random_stroll: super::super::components::BehaviorRandomStroll {
                interval: Some(120i32),
                priority: Some(BehaviorRandomStrollPriority {}),
                speed_multiplier: Some(BehaviorRandomStrollSpeedMultiplier {}),
                xz_dist: Some(10i32),
                y_dist: Some(7i32),
            },
            breathable: super::super::components::Breathable {
                breathe_blocks: None,
                breathes_air: Some(true),
                breathes_lava: Some(false),
                breathes_solids: Some(false),
                breathes_water: Some(false),
                can_dehydrate: Some(false),
                generates_bubbles: Some(true),
                inhale_time: Some(0f32),
                non_breathe_blocks: None,
                suffocate_time: Some(0i32),
                total_supply: Some(15i32),
            },
            collision_box: super::super::components::CollisionBox {
                height: Some(1.9f32),
                width: Some(0.6f32),
            },
            conditional_bandwidth_optimization:
                super::super::components::ConditionalBandwidthOptimization {
                    conditional_values: None,
                    default_values: None,
                },
            despawn: super::super::components::Despawn {
                despawn_from_chance: Some(true),
                despawn_from_distance: Some(DespawnDespawnFromDistance {
                    max_distance: None,
                    min_distance: None,
                }),
                despawn_from_inactivity: Some(true),
                despawn_from_simulation_edge: Some(true),
                filters: None,
                min_range_inactivity_timer: Some(30i32),
                min_range_random_chance: Some(800i32),
                remove_child_entities: Some(false),
            },
            equip_item: super::super::components::EquipItem {
                can_wear_armor: None,
                excluded_items: Some(vec![crate::types::BedrockValue::Object(
                    std::collections::HashMap::from([(
                        "item".to_string(),
                        crate::types::BedrockValue::String("minecraft:banner:15".to_string()),
                    )]),
                )]),
            },
            follow_range: super::super::components::FollowRange {
                max: None,
                min: None,
                value: crate::types::RangeOrVal::Fixed(64f32),
            },
            health: super::super::components::Health {
                max: Some(16f32),
                min: None,
                value: crate::types::RangeOrVal::Fixed(16f32),
            },
            hurt_on_condition: super::super::components::HurtOnCondition {
                damage_conditions: None,
            },
            inventory: super::super::components::Inventory {
                additional_slots_per_strength: Some(0i32),
                can_be_siphoned_from: Some(false),
                container_type: Some("none".to_string()),
                inventory_size: Some(8i32),
                private: Some(false),
                restrict_to_owner: Some(false),
            },
            is_hidden_when_invisible: super::super::components::IsHiddenWhenInvisible,
            jump_static: super::super::components::JumpStatic {
                jump_power: Some(0.42f32),
            },
            loot: super::super::components::Loot {
                table: "loot_tables/entities/piglin.json".to_string(),
            },
            movement_basic: super::super::components::MovementBasic {
                max_turn: Some(30f32),
            },
            nameable: super::super::components::Nameable {
                allow_name_tag_renaming: Some(true),
                always_show: Some(false),
                default_trigger: None,
                name_actions: None,
            },
            navigation_walk: super::super::components::NavigationWalk {
                avoid_damage_blocks: Some(false),
                avoid_portals: Some(false),
                avoid_sun: Some(false),
                avoid_water: Some(false),
                blocks_to_avoid: None,
                can_breach: Some(false),
                can_break_doors: Some(false),
                can_float: None,
                can_jump: Some(true),
                can_open_doors: Some(true),
                can_open_iron_doors: Some(false),
                can_pass_doors: Some(true),
                can_path_from_air: Some(false),
                can_path_over_lava: Some(false),
                can_path_over_water: Some(true),
                can_sink: Some(true),
                can_swim: Some(false),
                can_walk: Some(true),
                can_walk_in_lava: Some(false),
                is_amphibious: Some(false),
            },
            on_target_acquired: super::super::components::OnTargetAcquired {
                value: crate::types::BedrockValue::Null,
            },
            physics: super::super::components::Physics {
                has_collision: Some(true),
                has_gravity: Some(true),
                push_towards_closest_space: Some(false),
            },
            pushable: super::super::components::Pushable {
                is_pushable: Some(true),
                is_pushable_by_piston: Some(true),
            },
            shareables: super::super::components::Shareables {
                all_items: Some(false),
                all_items_max_amount: Some(-1i32),
                all_items_surplus_amount: Some(-1i32),
                all_items_want_amount: Some(-1i32),
                items: Some(vec![
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_axe".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_hoe".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_pickaxe".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_shovel".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_apple".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:appleEnchanted".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_carrot".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:gold_block".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:gold_nugget".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:raw_gold".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:gold_ore".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:nether_gold_ore".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:deepslate_gold_ore".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:raw_gold_block".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:gilded_blackstone".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:horsearmorgold".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_nautilus_armor".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:crossbow".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: Some(true),
                        craft_into: None,
                        item: Some("minecraft:porkchop".to_string()),
                        item_aux: None,
                        max_amount: Some(64i32),
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: Some(true),
                        craft_into: None,
                        item: Some("minecraft:cooked_porkchop".to_string()),
                        item_aux: None,
                        max_amount: Some(64i32),
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(7i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:0".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(9i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:1".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(9i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:2".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(9i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:3".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(9i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:4".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(9i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:5".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(9i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:carved_pumpkin".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(9i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:turtle_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(9i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(7i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:elytra".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(7i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:bell".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:clock".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:speckled_melon".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:light_weighted_pressure_plate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: Some(true),
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(7i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:stone_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(7i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:wooden_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:stone_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(7i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:wooden_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:shield".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(9i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                    ShareablesItems {
                        admire: Some(true),
                        barter: Some(true),
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:gold_ingot".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: Some(1i32),
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: None,
                        want_amount: None,
                    },
                ]),
                singular_pickup: Some(true),
            },
        })
        .id()
}
/// Component groups for this entity
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PiglinComponentGroup {
    AlertForAttackTargets,
    Angry,
    AttackCooldown,
    BecomeZombie,
    Hunter,
    InteractablePiglin,
    MeleeUnit,
    NotHunter,
    PiglinAdult,
    PiglinBaby,
    PiglinJockey,
    RangedUnit,
    StartZombification,
    TakeTargetAsResponseToBlockBreak,
    ZombificationSensor,
}
/// Events for this entity
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PiglinEvent {
    AdmireItemStartedEvent,
    AdmireItemStoppedEvent,
    AttackCooldownCompleteEvent,
    BecomeAngryEvent,
    BecomeCalmEvent,
    BecomeZombieEvent,
    ImportantBlockDestroyedEvent,
    EntityBorn,
    EntitySpawned,
    SpawnAdult,
    SpawnAdultMelee,
    SpawnAdultMeleeNoHunting,
    SpawnAdultNoHunting,
    SpawnAdultRanged,
    SpawnAdultRangedNoHunting,
    SpawnBaby,
    StartZombificationEvent,
    StopZombificationEvent,
}
