//! Generated definition for entity.
#[allow(unused_imports)]
use super::super::components::*;
use bevy_ecs::prelude::{Bundle, Commands, Entity};
/// Entity definition for `minecraft:zombie_pigman`
pub struct ZombiePigman;
impl ZombiePigman {
    /// The entity identifier
    pub const IDENTIFIER: &'static str = "minecraft:zombie_pigman";
    /// Whether this entity can spawn naturally
    pub const IS_SPAWNABLE: bool = true;
    /// Whether this entity can be summoned via commands
    pub const IS_SUMMONABLE: bool = true;
}
/// Component bundle for spawning a `minecraft:zombie_pigman`
#[derive(Bundle, Clone)]
pub struct ZombiePigmanBundle {
    pub attack: super::super::components::Attack,
    pub behavior_equip_item: super::super::components::BehaviorEquipItem,
    pub behavior_hurt_by_target: super::super::components::BehaviorHurtByTarget,
    pub behavior_look_at_player: super::super::components::BehaviorLookAtPlayer,
    pub behavior_melee_box_attack: super::super::components::BehaviorMeleeBoxAttack,
    pub behavior_mount_pathing: super::super::components::BehaviorMountPathing,
    pub behavior_pickup_items: super::super::components::BehaviorPickupItems,
    pub behavior_random_look_around: super::super::components::BehaviorRandomLookAround,
    pub behavior_random_stroll: super::super::components::BehaviorRandomStroll,
    pub behavior_stomp_turtle_egg: super::super::components::BehaviorStompTurtleEgg,
    pub behavior_use_kinetic_weapon: super::super::components::BehaviorUseKineticWeapon,
    pub breathable: super::super::components::Breathable,
    pub can_climb: super::super::components::CanClimb,
    pub collision_box: super::super::components::CollisionBox,
    pub conditional_bandwidth_optimization:
        super::super::components::ConditionalBandwidthOptimization,
    pub despawn: super::super::components::Despawn,
    pub equip_item: super::super::components::EquipItem,
    pub equipment: super::super::components::Equipment,
    pub fire_immune: super::super::components::FireImmune,
    pub health: super::super::components::Health,
    pub is_hidden_when_invisible: super::super::components::IsHiddenWhenInvisible,
    pub jump_static: super::super::components::JumpStatic,
    pub loot: super::super::components::Loot,
    pub movement: super::super::components::Movement,
    pub movement_basic: super::super::components::MovementBasic,
    pub nameable: super::super::components::Nameable,
    pub navigation_walk: super::super::components::NavigationWalk,
    pub physics: super::super::components::Physics,
    pub pushable: super::super::components::Pushable,
    pub shareables: super::super::components::Shareables,
    pub type_family: super::super::components::TypeFamily,
}
/// Spawn a new `minecraft:zombie_pigman` entity with default Bedrock components
pub fn spawn_zombie_pigman(commands: &mut Commands) -> Entity {
    commands
        .spawn(ZombiePigmanBundle {
            attack: super::super::components::Attack {
                damage: crate::types::RangeOrVal::Fixed(5f32),
                effect_duration: Some(crate::types::MolangOr::Value(0i32)),
                effect_name: None,
            },
            behavior_equip_item: super::super::components::BehaviorEquipItem {
                priority: Some(BehaviorEquipItemPriority {}),
            },
            behavior_hurt_by_target: super::super::components::BehaviorHurtByTarget {
                alert_same_type: Some(false),
                entity_types: None,
                hurt_owner: Some(false),
                priority: Some(BehaviorHurtByTargetPriority {}),
            },
            behavior_look_at_player: super::super::components::BehaviorLookAtPlayer {
                angle_of_view_horizontal: Some(360i32),
                angle_of_view_vertical: Some(360i32),
                look_distance: Some(6f32),
                look_time: None,
                priority: Some(BehaviorLookAtPlayerPriority {}),
                probability: Some(0.02f32),
                target_distance: None,
            },
            behavior_melee_box_attack: super::super::components::BehaviorMeleeBoxAttack {
                attack_once: Some(false),
                attack_types: None,
                can_spread_on_fire: Some(false),
                control_flags: None,
                cooldown_time: Some(1f32),
                horizontal_reach: Some(0.8f32),
                inner_boundary_time_increase: Some(0.25f32),
                max_dist: None,
                max_path_time: Some(0.55f32),
                melee_fov: Some(90f32),
                min_path_time: Some(0.2f32),
                on_attack: None,
                on_kill: None,
                outer_boundary_time_increase: Some(0.5f32),
                path_fail_time_increase: Some(0.75f32),
                path_inner_boundary: Some(16f32),
                path_outer_boundary: Some(32f32),
                priority: Some(BehaviorMeleeBoxAttackPriority {}),
                random_stop_interval: Some(0i32),
                reach_multiplier: None,
                require_complete_path: Some(false),
                set_persistent: None,
                speed_multiplier: Some(BehaviorMeleeBoxAttackSpeedMultiplier {}),
                target_dist: None,
                track_target: Some(false),
                x_max_rotation: Some(30f32),
                y_max_head_rotation: Some(30f32),
            },
            behavior_mount_pathing: super::super::components::BehaviorMountPathing {
                priority: Some(BehaviorMountPathingPriority {}),
                speed_multiplier: Some(BehaviorMountPathingSpeedMultiplier {}),
                target_dist: Some(0f32),
                track_target: Some(true),
            },
            behavior_pickup_items: super::super::components::BehaviorPickupItems {
                can_pickup_any_item: Some(true),
                can_pickup_to_hand_or_equipment: Some(true),
                cooldown_after_being_attacked: None,
                excluded_items: None,
                goal_radius: Some(2f32),
                max_dist: Some(3f32),
                pickup_based_on_chance: Some(true),
                pickup_same_items_as_in_hand: None,
                priority: Some(BehaviorPickupItemsPriority {}),
                search_height: None,
                speed_multiplier: Some(BehaviorPickupItemsSpeedMultiplier {}),
                track_target: Some(false),
            },
            behavior_random_look_around: super::super::components::BehaviorRandomLookAround {
                angle_of_view_horizontal: None,
                angle_of_view_vertical: None,
                look_distance: None,
                look_time: None,
                priority: Some(BehaviorRandomLookAroundPriority {}),
                probability: None,
            },
            behavior_random_stroll: super::super::components::BehaviorRandomStroll {
                interval: Some(120i32),
                priority: Some(BehaviorRandomStrollPriority {}),
                speed_multiplier: Some(BehaviorRandomStrollSpeedMultiplier {}),
                xz_dist: Some(10i32),
                y_dist: Some(7i32),
            },
            behavior_stomp_turtle_egg: super::super::components::BehaviorStompTurtleEgg {
                goal_radius: Some(1.14f32),
                interval: Some(20i32),
                priority: Some(BehaviorStompTurtleEggPriority {}),
                search_count: None,
                search_height: Some(2i32),
                search_range: Some(10i32),
                speed_multiplier: Some(BehaviorStompTurtleEggSpeedMultiplier {}),
            },
            behavior_use_kinetic_weapon: super::super::components::BehaviorUseKineticWeapon {
                approach_distance: Some(10f32),
                attack_once: Some(false),
                cooldown_distance: Some(0f32),
                cooldown_speed_multiplier: Some(1.5f32),
                cooldown_time: Some(1f32),
                hijack_mount_navigation: Some(true),
                max_path_time: Some(0.55f32),
                melee_fov: Some(90f32),
                min_path_time: Some(0.2f32),
                outer_boundary_time_increase: Some(0.5f32),
                path_fail_time_increase: Some(0.75f32),
                path_inner_boundary: Some(16f32),
                path_outer_boundary: Some(32f32),
                priority: Some(BehaviorUseKineticWeaponPriority {}),
                random_stop_interval: Some(0i32),
                reposition_distance: Some(0f32),
                reposition_speed_multiplier: Some(1f32),
                require_complete_path: Some(false),
                speed_multiplier: Some(BehaviorUseKineticWeaponSpeedMultiplier {}),
                track_target: Some(true),
                weapon_min_speed_multiplier: Some(0.2f32),
                weapon_reach_multiplier: Some(0.5f32),
                x_max_rotation: Some(30f32),
                y_max_head_rotation: Some(30f32),
            },
            breathable: super::super::components::Breathable {
                breathe_blocks: None,
                breathes_air: Some(true),
                breathes_lava: Some(false),
                breathes_solids: Some(false),
                breathes_water: Some(true),
                can_dehydrate: Some(false),
                generates_bubbles: Some(true),
                inhale_time: Some(0f32),
                non_breathe_blocks: None,
                suffocate_time: Some(0i32),
                total_supply: Some(15i32),
            },
            can_climb: super::super::components::CanClimb,
            collision_box: super::super::components::CollisionBox {
                height: Some(1.9f32),
                width: Some(0.6f32),
            },
            conditional_bandwidth_optimization:
                super::super::components::ConditionalBandwidthOptimization {
                    conditional_values: None,
                    default_values: None,
                },
            despawn: super::super::components::Despawn {
                despawn_from_chance: Some(true),
                despawn_from_distance: Some(DespawnDespawnFromDistance {
                    max_distance: None,
                    min_distance: None,
                }),
                despawn_from_inactivity: Some(true),
                despawn_from_simulation_edge: Some(true),
                filters: None,
                min_range_inactivity_timer: Some(30i32),
                min_range_random_chance: Some(800i32),
                remove_child_entities: Some(false),
            },
            equip_item: super::super::components::EquipItem {
                can_wear_armor: None,
                excluded_items: None,
            },
            equipment: super::super::components::Equipment {
                slot_drop_chance: None,
                table: Some("loot_tables/entities/zombie_pigman_gear.json".to_string()),
            },
            fire_immune: super::super::components::FireImmune,
            health: super::super::components::Health {
                max: Some(20f32),
                min: None,
                value: crate::types::RangeOrVal::Fixed(20f32),
            },
            is_hidden_when_invisible: super::super::components::IsHiddenWhenInvisible,
            jump_static: super::super::components::JumpStatic {
                jump_power: Some(0.42f32),
            },
            loot: super::super::components::Loot {
                table: "loot_tables/entities/zombie_pigman.json".to_string(),
            },
            movement: super::super::components::Movement {
                max: None,
                min: None,
                value: crate::types::RangeOrVal::Fixed(0.23f32),
            },
            movement_basic: super::super::components::MovementBasic {
                max_turn: Some(30f32),
            },
            nameable: super::super::components::Nameable {
                allow_name_tag_renaming: Some(true),
                always_show: Some(false),
                default_trigger: None,
                name_actions: None,
            },
            navigation_walk: super::super::components::NavigationWalk {
                avoid_damage_blocks: Some(false),
                avoid_portals: Some(true),
                avoid_sun: Some(false),
                avoid_water: Some(true),
                blocks_to_avoid: None,
                can_breach: Some(false),
                can_break_doors: Some(false),
                can_float: None,
                can_jump: Some(true),
                can_open_doors: Some(true),
                can_open_iron_doors: Some(false),
                can_pass_doors: Some(true),
                can_path_from_air: Some(false),
                can_path_over_lava: Some(true),
                can_path_over_water: Some(false),
                can_sink: Some(true),
                can_swim: Some(false),
                can_walk: Some(true),
                can_walk_in_lava: Some(false),
                is_amphibious: Some(true),
            },
            physics: super::super::components::Physics {
                has_collision: Some(true),
                has_gravity: Some(true),
                push_towards_closest_space: Some(false),
            },
            pushable: super::super::components::Pushable {
                is_pushable: Some(true),
                is_pushable_by_piston: Some(true),
            },
            shareables: super::super::components::Shareables {
                all_items: Some(false),
                all_items_max_amount: Some(-1i32),
                all_items_surplus_amount: Some(-1i32),
                all_items_want_amount: Some(-1i32),
                items: Some(vec![
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:stone_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:wooden_sword".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:stone_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:wooden_spear".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:turtle_helmet".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(7i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:0".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:skull:1".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:carved_pumpkin".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(8i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_chestplate".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_leggings".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:netherite_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(0i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:diamond_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(1i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:iron_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(2i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:chainmail_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(3i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:golden_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(4i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:copper_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(5i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                    ShareablesItems {
                        admire: None,
                        barter: None,
                        consume_item: None,
                        craft_into: None,
                        item: Some("minecraft:leather_boots".to_string()),
                        item_aux: None,
                        max_amount: None,
                        pickup_limit: None,
                        pickup_only: None,
                        priority: Some(6i32),
                        stored_in_inventory: None,
                        surplus_amount: Some(1i32),
                        want_amount: Some(1i32),
                    },
                ]),
                singular_pickup: Some(false),
            },
            type_family: super::super::components::TypeFamily {
                family: vec![
                    "zombie_pigman".to_string(),
                    "undead".to_string(),
                    "monster".to_string(),
                    "mob".to_string(),
                ],
            },
        })
        .id()
}
/// Component groups for this entity
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZombiePigmanComponentGroup {
    PigZombieAdult,
    PigZombieAngry,
    PigZombieBaby,
    PigZombieCalm,
    StriderJockey,
}
/// Events for this entity
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ZombiePigmanEvent {
    BecomeAngry,
    EntitySpawned,
    EntityTransformed,
    OnCalm,
    SpawnAsStriderJockey,
    SpawnAdult,
    SpawnBaby,
}
