// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(clippy::all)]
use super::super::packets::*;
use super::*;
use crate::bedrock::codec::BedrockCodec;
use ::bitflags::bitflags;
use bytes::{Buf, BufMut};
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TransactionLegacyLegacyTransactionsItemChangedSlotsItem {
    pub slot_id: u8,
}
impl crate::bedrock::codec::BedrockCodec
    for TransactionLegacyLegacyTransactionsItemChangedSlotsItem
{
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.slot_id.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let _ = buf;
        let slot_id = <u8 as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        Ok(Self { slot_id })
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TransactionLegacyLegacyTransactionsItem {
    pub container_id: u8,
    pub changed_slots: Vec<TransactionLegacyLegacyTransactionsItemChangedSlotsItem>,
}
impl crate::bedrock::codec::BedrockCodec for TransactionLegacyLegacyTransactionsItem {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.container_id.encode(buf)?;
        let len = self.changed_slots.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        for item in &self.changed_slots {
            item.encode(buf)?;
        }
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let _ = buf;
        let container_id = <u8 as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let changed_slots = {
            let raw =
                <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0 as i64;
            if raw < 0 {
                return Err(std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    "array length cannot be negative",
                ));
            }
            let len = raw as usize;
            let mut tmp_vec = Vec::with_capacity(len);
            for _ in 0..len {
                tmp_vec
                    .push(
                        <TransactionLegacyLegacyTransactionsItemChangedSlotsItem as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    );
            }
            tmp_vec
        };
        Ok(Self {
            container_id,
            changed_slots,
        })
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TransactionLegacy {
    pub legacy_request_id: i32,
    pub legacy_transactions: Option<Vec<TransactionLegacyLegacyTransactionsItem>>,
}
impl crate::bedrock::codec::BedrockCodec for TransactionLegacy {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        crate::bedrock::codec::ZigZag32(self.legacy_request_id).encode(buf)?;
        if let Some(v) = &self.legacy_transactions {
            v.encode(buf)?;
        }
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let _ = buf;
        let legacy_request_id =
            <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let legacy_transactions = if (legacy_request_id) != 0 {
            Some({
                let raw =
                    <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                        buf,
                        (),
                    )?
                    .0 as i64;
                if raw < 0 {
                    return Err(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "array length cannot be negative",
                    ));
                }
                let len = raw as usize;
                let mut tmp_vec = Vec::with_capacity(len);
                for _ in 0..len {
                    tmp_vec
                        .push(
                            <TransactionLegacyLegacyTransactionsItem as crate::bedrock::codec::BedrockCodec>::decode(
                                buf,
                                (),
                            )?,
                        );
                }
                tmp_vec
            })
        } else {
            None
        };
        Ok(Self {
            legacy_request_id,
            legacy_transactions,
        })
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TransactionTransactionType {
    Normal = 0,
    InventoryMismatch = 1,
    ItemUse = 2,
    ItemUseOnEntity = 3,
    ItemRelease = 4,
}
impl crate::bedrock::codec::BedrockCodec for TransactionTransactionType {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = *self as i32;
        crate::bedrock::codec::VarInt(val as i32).encode(buf)
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let val = raw.0 as i32;
        match val {
            0 => Ok(TransactionTransactionType::Normal),
            1 => Ok(TransactionTransactionType::InventoryMismatch),
            2 => Ok(TransactionTransactionType::ItemUse),
            3 => Ok(TransactionTransactionType::ItemUseOnEntity),
            4 => Ok(TransactionTransactionType::ItemRelease),
            _ => Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!(
                    "Invalid enum value for {}: {}",
                    stringify!(TransactionTransactionType),
                    val
                ),
            )),
        }
    }
}
impl Default for TransactionTransactionType {
    fn default() -> Self {
        Self::Normal
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TransactionActionsItemSourceType {
    Container = 0,
    Global = 1,
    WorldInteraction = 2,
    Creative = 3,
    CraftSlot = 100,
    Craft = 99999,
}
impl crate::bedrock::codec::BedrockCodec for TransactionActionsItemSourceType {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = *self as i32;
        crate::bedrock::codec::VarInt(val as i32).encode(buf)
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let val = raw.0 as i32;
        match val {
            0 => Ok(TransactionActionsItemSourceType::Container),
            1 => Ok(TransactionActionsItemSourceType::Global),
            2 => Ok(TransactionActionsItemSourceType::WorldInteraction),
            3 => Ok(TransactionActionsItemSourceType::Creative),
            100 => Ok(TransactionActionsItemSourceType::CraftSlot),
            99999 => Ok(TransactionActionsItemSourceType::Craft),
            _ => Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!(
                    "Invalid enum value for {}: {}",
                    stringify!(TransactionActionsItemSourceType),
                    val
                ),
            )),
        }
    }
}
impl Default for TransactionActionsItemSourceType {
    fn default() -> Self {
        Self::Container
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TransactionActionsItemContentContainer {
    pub inventory_id: WindowIdVarint,
}
impl crate::bedrock::codec::BedrockCodec for TransactionActionsItemContentContainer {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.inventory_id.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let _ = buf;
        let inventory_id =
            <WindowIdVarint as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        Ok(Self { inventory_id })
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TransactionActionsItemContentCraft {
    pub action: i32,
}
impl crate::bedrock::codec::BedrockCodec for TransactionActionsItemContentCraft {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        crate::bedrock::codec::VarInt(self.action).encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let _ = buf;
        let action =
            <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        Ok(Self { action })
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TransactionActionsItemContentWorldInteraction {
    pub flags: i32,
}
impl crate::bedrock::codec::BedrockCodec for TransactionActionsItemContentWorldInteraction {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        crate::bedrock::codec::VarInt(self.flags).encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let _ = buf;
        let flags = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?
        .0;
        Ok(Self { flags })
    }
}
#[derive(Debug, Clone, PartialEq)]
pub enum TransactionActionsItemContent {
    Container(TransactionActionsItemContentContainer),
    Craft(TransactionActionsItemContentCraft),
    CraftSlot(TransactionActionsItemContentCraft),
    WorldInteraction(TransactionActionsItemContentWorldInteraction),
}
impl Default for TransactionActionsItemContent {
    fn default() -> Self {
        Self::Container(Default::default())
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TransactionActionsItem {
    pub source_type: TransactionActionsItemSourceType,
    pub content: Option<TransactionActionsItemContent>,
    pub slot: i32,
    pub old_item: Item,
    pub new_item: Item,
}
#[derive(Debug, Clone)]
pub struct TransactionActionsItemArgs {
    pub shield_item_id: i32,
}
impl<'a> From<&'a crate::bedrock::context::BedrockSession> for TransactionActionsItemArgs {
    fn from(source: &'a crate::bedrock::context::BedrockSession) -> Self {
        Self {
            shield_item_id: source.shield_item_id,
        }
    }
}
impl crate::bedrock::codec::BedrockCodec for TransactionActionsItem {
    type Args = TransactionActionsItemArgs;
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.source_type.encode(buf)?;
        if let Some(v) = &self.content {
            match v {
                TransactionActionsItemContent::Container(v) => {
                    v.encode(buf)?;
                }
                TransactionActionsItemContent::Craft(v) => {
                    v.encode(buf)?;
                }
                TransactionActionsItemContent::CraftSlot(v) => {
                    v.encode(buf)?;
                }
                TransactionActionsItemContent::WorldInteraction(v) => {
                    v.encode(buf)?;
                }
            }
        }
        crate::bedrock::codec::VarInt(self.slot).encode(buf)?;
        self.old_item.encode(buf)?;
        self.new_item.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B, args: Self::Args) -> Result<Self, std::io::Error> {
        let _ = buf;
        let source_type =
            <TransactionActionsItemSourceType as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?;
        let content = match source_type {
            TransactionActionsItemSourceType::Container => {
                Some(
                    TransactionActionsItemContent::Container(
                        <TransactionActionsItemContentContainer as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    ),
                )
            }
            TransactionActionsItemSourceType::Craft => {
                Some(
                    TransactionActionsItemContent::Craft(
                        <TransactionActionsItemContentCraft as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    ),
                )
            }
            TransactionActionsItemSourceType::CraftSlot => {
                Some(
                    TransactionActionsItemContent::CraftSlot(
                        <TransactionActionsItemContentCraft as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    ),
                )
            }
            TransactionActionsItemSourceType::WorldInteraction => {
                Some(
                    TransactionActionsItemContent::WorldInteraction(
                        <TransactionActionsItemContentWorldInteraction as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    ),
                )
            }
            _ => None,
        };
        let slot = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?
        .0;
        let old_item = <Item as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            ItemArgs {
                shield_item_id: args.shield_item_id,
            },
        )?;
        let new_item = <Item as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            ItemArgs {
                shield_item_id: args.shield_item_id,
            },
        )?;
        Ok(Self {
            source_type,
            content,
            slot,
            old_item,
            new_item,
        })
    }
}
pub type TransactionActions = Vec<TransactionActionsItem>;
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TransactionTransactionDataItemReleaseActionType {
    Release = 0,
    Consume = 1,
}
impl crate::bedrock::codec::BedrockCodec for TransactionTransactionDataItemReleaseActionType {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = *self as i32;
        crate::bedrock::codec::VarInt(val as i32).encode(buf)
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let val = raw.0 as i32;
        match val {
            0 => Ok(TransactionTransactionDataItemReleaseActionType::Release),
            1 => Ok(TransactionTransactionDataItemReleaseActionType::Consume),
            _ => Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!(
                    "Invalid enum value for {}: {}",
                    stringify!(TransactionTransactionDataItemReleaseActionType),
                    val
                ),
            )),
        }
    }
}
impl Default for TransactionTransactionDataItemReleaseActionType {
    fn default() -> Self {
        Self::Release
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TransactionTransactionDataItemRelease {
    pub action_type: TransactionTransactionDataItemReleaseActionType,
    pub hotbar_slot: i32,
    pub held_item: Item,
    pub head_pos: Vec3F,
}
#[derive(Debug, Clone)]
pub struct TransactionTransactionDataItemReleaseArgs {
    pub shield_item_id: i32,
}
impl<'a> From<&'a crate::bedrock::context::BedrockSession>
    for TransactionTransactionDataItemReleaseArgs
{
    fn from(source: &'a crate::bedrock::context::BedrockSession) -> Self {
        Self {
            shield_item_id: source.shield_item_id,
        }
    }
}
impl crate::bedrock::codec::BedrockCodec for TransactionTransactionDataItemRelease {
    type Args = TransactionTransactionDataItemReleaseArgs;
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.action_type.encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.hotbar_slot).encode(buf)?;
        self.held_item.encode(buf)?;
        self.head_pos.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B, args: Self::Args) -> Result<Self, std::io::Error> {
        let _ = buf;
        let action_type = <TransactionTransactionDataItemReleaseActionType as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let hotbar_slot =
            <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let held_item = <Item as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            ItemArgs {
                shield_item_id: args.shield_item_id,
            },
        )?;
        let head_pos = <Vec3F as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        Ok(Self {
            action_type,
            hotbar_slot,
            held_item,
            head_pos,
        })
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TransactionUseItemActionType {
    ClickBlock = 0,
    ClickAir = 1,
    BreakBlock = 2,
    Attack = 3,
}
impl crate::bedrock::codec::BedrockCodec for TransactionUseItemActionType {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = *self as i32;
        crate::bedrock::codec::VarInt(val as i32).encode(buf)
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let val = raw.0 as i32;
        match val {
            0 => Ok(TransactionUseItemActionType::ClickBlock),
            1 => Ok(TransactionUseItemActionType::ClickAir),
            2 => Ok(TransactionUseItemActionType::BreakBlock),
            3 => Ok(TransactionUseItemActionType::Attack),
            _ => Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!(
                    "Invalid enum value for {}: {}",
                    stringify!(TransactionUseItemActionType),
                    val
                ),
            )),
        }
    }
}
impl Default for TransactionUseItemActionType {
    fn default() -> Self {
        Self::ClickBlock
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TransactionUseItemTriggerType {
    Unknown = 0,
    PlayerInput = 1,
    SimulationTick = 2,
}
impl crate::bedrock::codec::BedrockCodec for TransactionUseItemTriggerType {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = *self as i32;
        crate::bedrock::codec::VarInt(val as i32).encode(buf)
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let val = raw.0 as i32;
        match val {
            0 => Ok(TransactionUseItemTriggerType::Unknown),
            1 => Ok(TransactionUseItemTriggerType::PlayerInput),
            2 => Ok(TransactionUseItemTriggerType::SimulationTick),
            _ => Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!(
                    "Invalid enum value for {}: {}",
                    stringify!(TransactionUseItemTriggerType),
                    val
                ),
            )),
        }
    }
}
impl Default for TransactionUseItemTriggerType {
    fn default() -> Self {
        Self::Unknown
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TransactionUseItemClientPrediction {
    Failure = 0,
    Success = 1,
}
impl crate::bedrock::codec::BedrockCodec for TransactionUseItemClientPrediction {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = *self as i32;
        crate::bedrock::codec::VarInt(val as i32).encode(buf)
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let val = raw.0 as i32;
        match val {
            0 => Ok(TransactionUseItemClientPrediction::Failure),
            1 => Ok(TransactionUseItemClientPrediction::Success),
            _ => Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!(
                    "Invalid enum value for {}: {}",
                    stringify!(TransactionUseItemClientPrediction),
                    val
                ),
            )),
        }
    }
}
impl Default for TransactionUseItemClientPrediction {
    fn default() -> Self {
        Self::Failure
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TransactionUseItem {
    pub action_type: TransactionUseItemActionType,
    pub trigger_type: TransactionUseItemTriggerType,
    pub block_position: BlockCoordinates,
    pub face: i32,
    pub hotbar_slot: i32,
    pub held_item: Item,
    pub player_pos: Vec3F,
    pub click_pos: Vec3F,
    pub block_runtime_id: i32,
    pub client_prediction: i32,
}
#[derive(Debug, Clone)]
pub struct TransactionUseItemArgs {
    pub shield_item_id: i32,
}
impl<'a> From<&'a crate::bedrock::context::BedrockSession> for TransactionUseItemArgs {
    fn from(source: &'a crate::bedrock::context::BedrockSession) -> Self {
        Self {
            shield_item_id: source.shield_item_id,
        }
    }
}
impl crate::bedrock::codec::BedrockCodec for TransactionUseItem {
    type Args = TransactionUseItemArgs;
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.action_type.encode(buf)?;
        self.trigger_type.encode(buf)?;
        self.block_position.encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.face).encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.hotbar_slot).encode(buf)?;
        self.held_item.encode(buf)?;
        self.player_pos.encode(buf)?;
        self.click_pos.encode(buf)?;
        crate::bedrock::codec::VarInt(self.block_runtime_id).encode(buf)?;
        crate::bedrock::codec::VarInt(self.client_prediction).encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B, args: Self::Args) -> Result<Self, std::io::Error> {
        let _ = buf;
        let action_type =
            <TransactionUseItemActionType as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let trigger_type =
            <TransactionUseItemTriggerType as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?;
        let block_position =
            <BlockCoordinates as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let face =
            <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let hotbar_slot =
            <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let held_item = <Item as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            ItemArgs {
                shield_item_id: args.shield_item_id,
            },
        )?;
        let player_pos = <Vec3F as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let click_pos = <Vec3F as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let block_runtime_id =
            <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let client_prediction =
            <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        Ok(Self {
            action_type,
            trigger_type,
            block_position,
            face,
            hotbar_slot,
            held_item,
            player_pos,
            click_pos,
            block_runtime_id,
            client_prediction,
        })
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum TransactionTransactionDataItemUseOnEntityActionType {
    Interact = 0,
    Attack = 1,
}
impl crate::bedrock::codec::BedrockCodec for TransactionTransactionDataItemUseOnEntityActionType {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = *self as i32;
        crate::bedrock::codec::VarInt(val as i32).encode(buf)
    }
    fn decode<B: bytes::Buf>(buf: &mut B, _args: Self::Args) -> Result<Self, std::io::Error> {
        let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let val = raw.0 as i32;
        match val {
            0 => Ok(TransactionTransactionDataItemUseOnEntityActionType::Interact),
            1 => Ok(TransactionTransactionDataItemUseOnEntityActionType::Attack),
            _ => Err(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!(
                    "Invalid enum value for {}: {}",
                    stringify!(TransactionTransactionDataItemUseOnEntityActionType),
                    val
                ),
            )),
        }
    }
}
impl Default for TransactionTransactionDataItemUseOnEntityActionType {
    fn default() -> Self {
        Self::Interact
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct TransactionTransactionDataItemUseOnEntity {
    pub entity_runtime_id: i64,
    pub action_type: TransactionTransactionDataItemUseOnEntityActionType,
    pub hotbar_slot: i32,
    pub held_item: Item,
    pub player_pos: Vec3F,
    pub click_pos: Vec3F,
}
#[derive(Debug, Clone)]
pub struct TransactionTransactionDataItemUseOnEntityArgs {
    pub shield_item_id: i32,
}
impl<'a> From<&'a crate::bedrock::context::BedrockSession>
    for TransactionTransactionDataItemUseOnEntityArgs
{
    fn from(source: &'a crate::bedrock::context::BedrockSession) -> Self {
        Self {
            shield_item_id: source.shield_item_id,
        }
    }
}
impl crate::bedrock::codec::BedrockCodec for TransactionTransactionDataItemUseOnEntity {
    type Args = TransactionTransactionDataItemUseOnEntityArgs;
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        crate::bedrock::codec::VarLong(self.entity_runtime_id).encode(buf)?;
        self.action_type.encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.hotbar_slot).encode(buf)?;
        self.held_item.encode(buf)?;
        self.player_pos.encode(buf)?;
        self.click_pos.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B, args: Self::Args) -> Result<Self, std::io::Error> {
        let _ = buf;
        let entity_runtime_id =
            <crate::bedrock::codec::VarLong as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let action_type = <TransactionTransactionDataItemUseOnEntityActionType as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let hotbar_slot =
            <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let held_item = <Item as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            ItemArgs {
                shield_item_id: args.shield_item_id,
            },
        )?;
        let player_pos = <Vec3F as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let click_pos = <Vec3F as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        Ok(Self {
            entity_runtime_id,
            action_type,
            hotbar_slot,
            held_item,
            player_pos,
            click_pos,
        })
    }
}
#[derive(Debug, Clone, PartialEq)]
pub enum TransactionTransactionData {
    InventoryMismatch,
    ItemRelease(Box<TransactionTransactionDataItemRelease>),
    ItemUse(Box<TransactionUseItem>),
    ItemUseOnEntity(Box<TransactionTransactionDataItemUseOnEntity>),
    Normal,
}
impl Default for TransactionTransactionData {
    fn default() -> Self {
        Self::InventoryMismatch
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Transaction {
    pub legacy: TransactionLegacy,
    pub transaction_type: TransactionTransactionType,
    pub actions: TransactionActions,
    pub transaction_data: Option<TransactionTransactionData>,
}
#[derive(Debug, Clone)]
pub struct TransactionArgs {
    pub shield_item_id: i32,
}
impl<'a> From<&'a crate::bedrock::context::BedrockSession> for TransactionArgs {
    fn from(source: &'a crate::bedrock::context::BedrockSession) -> Self {
        Self {
            shield_item_id: source.shield_item_id,
        }
    }
}
impl crate::bedrock::codec::BedrockCodec for Transaction {
    type Args = TransactionArgs;
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.legacy.encode(buf)?;
        self.transaction_type.encode(buf)?;
        let len = self.actions.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        for item in &self.actions {
            item.encode(buf)?;
        }
        if let Some(v) = &self.transaction_data {
            match v {
                TransactionTransactionData::InventoryMismatch => {}
                TransactionTransactionData::ItemRelease(v) => {
                    v.encode(buf)?;
                }
                TransactionTransactionData::ItemUse(v) => {
                    v.encode(buf)?;
                }
                TransactionTransactionData::ItemUseOnEntity(v) => {
                    v.encode(buf)?;
                }
                TransactionTransactionData::Normal => {}
            }
        }
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B, args: Self::Args) -> Result<Self, std::io::Error> {
        let _ = buf;
        let legacy = <TransactionLegacy as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let transaction_type =
            <TransactionTransactionType as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let actions = {
            let res: TransactionActions = {
                let raw =
                    <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                        buf,
                        (),
                    )?
                    .0 as i64;
                if raw < 0 {
                    return Err(std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "array length cannot be negative",
                    ));
                }
                let len = raw as usize;
                let mut tmp_vec = Vec::with_capacity(len);
                for _ in 0..len {
                    tmp_vec.push(
                        <TransactionActionsItem as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            TransactionActionsItemArgs {
                                shield_item_id: args.shield_item_id,
                            },
                        )?,
                    );
                }
                tmp_vec
            };
            res
        };
        let transaction_data = match transaction_type {
            TransactionTransactionType::InventoryMismatch => {
                Some(TransactionTransactionData::InventoryMismatch)
            }
            TransactionTransactionType::ItemRelease => {
                Some(
                    TransactionTransactionData::ItemRelease(
                        Box::new(
                            <TransactionTransactionDataItemRelease as crate::bedrock::codec::BedrockCodec>::decode(
                                buf,
                                TransactionTransactionDataItemReleaseArgs {
                                    shield_item_id: args.shield_item_id,
                                },
                            )?,
                        ),
                    ),
                )
            }
            TransactionTransactionType::ItemUse => {
                Some(
                    TransactionTransactionData::ItemUse(
                        Box::new(
                            <TransactionUseItem as crate::bedrock::codec::BedrockCodec>::decode(
                                buf,
                                TransactionUseItemArgs {
                                    shield_item_id: args.shield_item_id,
                                },
                            )?,
                        ),
                    ),
                )
            }
            TransactionTransactionType::ItemUseOnEntity => {
                Some(
                    TransactionTransactionData::ItemUseOnEntity(
                        Box::new(
                            <TransactionTransactionDataItemUseOnEntity as crate::bedrock::codec::BedrockCodec>::decode(
                                buf,
                                TransactionTransactionDataItemUseOnEntityArgs {
                                    shield_item_id: args.shield_item_id,
                                },
                            )?,
                        ),
                    ),
                )
            }
            TransactionTransactionType::Normal => {
                Some(TransactionTransactionData::Normal)
            }
        };
        Ok(Self {
            legacy,
            transaction_type,
            actions,
            transaction_data,
        })
    }
}
