//! Biome enum for Minecraft world generation.
//!
//! These biome IDs match vanilla Minecraft.

/// Biome IDs matching vanilla Minecraft.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum Biome {
    Ocean = 0,
    Plains = 1,
    Desert = 2,
    WindsweptHills = 3,
    Forest = 4,
    Taiga = 5,
    Swamp = 6,
    River = 7,
    NetherWastes = 8,
    TheEnd = 9,
    FrozenOcean = 10,
    FrozenRiver = 11,
    SnowyPlains = 12,
    SnowyMountains = 13,
    MushroomFields = 14,
    MushroomFieldShore = 15,
    Beach = 16,
    DesertHills = 17,
    WoodedHills = 18,
    TaigaHills = 19,
    MountainEdge = 20,
    Jungle = 21,
    JungleHills = 22,
    SparseJungle = 23,
    DeepOcean = 24,
    StonyShore = 25,
    SnowyBeach = 26,
    BirchForest = 27,
    BirchForestHills = 28,
    DarkForest = 29,
    SnowyTaiga = 30,
    SnowyTaigaHills = 31,
    OldGrowthPineTaiga = 32,
    OldGrowthPineTaigaHills = 33,
    WindsweptForest = 34,
    Savanna = 35,
    SavannaPlateau = 36,
    Badlands = 37,
    WoodedBadlands = 38,
    BadlandsPlateau = 39,
    SmallEndIslands = 40,
    EndMidlands = 41,
    EndHighlands = 42,
    EndBarrens = 43,
    WarmOcean = 44,
    LukewarmOcean = 45,
    ColdOcean = 46,
    DeepWarmOcean = 47,
    DeepLukewarmOcean = 48,
    DeepColdOcean = 49,
    DeepFrozenOcean = 50,
    TheVoid = 127,
    SunflowerPlains = 129,
    GravellyMountains = 131,
    FlowerForest = 132,
    IceSpikes = 140,
    TallBirchForest = 155,
    OldGrowthSpruceTaiga = 160,
    WindsweptSavanna = 163,
    ErodedBadlands = 165,
    BambooJungle = 168,
    SoulSandValley = 170,
    CrimsonForest = 171,
    WarpedForest = 172,
    BasaltDeltas = 173,
    DripstoneCaves = 174,
    LushCaves = 175,
    Meadow = 177,
    Grove = 178,
    SnowySlopes = 179,
    JaggedPeaks = 180,
    FrozenPeaks = 181,
    StonyPeaks = 182,
    DeepDark = 183,
    MangroveSwamp = 184,
    CherryGrove = 185,
    PaleGarden = 186,
}

impl Default for Biome {
    fn default() -> Self {
        Self::Plains
    }
}

impl From<u8> for Biome {
    fn from(id: u8) -> Self {
        // Safety: we validate the range
        match id {
            0 => Self::Ocean,
            1 => Self::Plains,
            2 => Self::Desert,
            3 => Self::WindsweptHills,
            4 => Self::Forest,
            5 => Self::Taiga,
            6 => Self::Swamp,
            7 => Self::River,
            8 => Self::NetherWastes,
            9 => Self::TheEnd,
            10 => Self::FrozenOcean,
            11 => Self::FrozenRiver,
            12 => Self::SnowyPlains,
            27 => Self::BirchForest,
            29 => Self::DarkForest,
            30 => Self::SnowyTaiga,
            32 => Self::OldGrowthPineTaiga,
            35 => Self::Savanna,
            37 => Self::Badlands,
            44 => Self::WarmOcean,
            45 => Self::LukewarmOcean,
            46 => Self::ColdOcean,
            48 => Self::DeepLukewarmOcean,
            49 => Self::DeepColdOcean,
            50 => Self::DeepFrozenOcean,
            177 => Self::Meadow,
            178 => Self::Grove,
            179 => Self::SnowySlopes,
            180 => Self::JaggedPeaks,
            181 => Self::FrozenPeaks,
            182 => Self::StonyPeaks,
            185 => Self::CherryGrove,
            _ => Self::Plains,
        }
    }
}

impl Biome {
    /// Get biome from its vanilla name (e.g., "desert", "frozen_peaks").
    pub fn from_name(name: &str) -> Option<Self> {
        // Strip minecraft: prefix if present
        let name = name.strip_prefix("minecraft:").unwrap_or(name);

        Some(match name {
            "ocean" => Self::Ocean,
            "plains" => Self::Plains,
            "desert" => Self::Desert,
            "windswept_hills" => Self::WindsweptHills,
            "forest" => Self::Forest,
            "taiga" => Self::Taiga,
            "swamp" => Self::Swamp,
            "river" => Self::River,
            "nether_wastes" => Self::NetherWastes,
            "the_end" => Self::TheEnd,
            "frozen_ocean" => Self::FrozenOcean,
            "frozen_river" => Self::FrozenRiver,
            "snowy_plains" => Self::SnowyPlains,
            "snowy_mountains" => Self::SnowyMountains,
            "mushroom_fields" => Self::MushroomFields,
            "mushroom_field_shore" => Self::MushroomFieldShore,
            "beach" => Self::Beach,
            "desert_hills" => Self::DesertHills,
            "wooded_hills" => Self::WoodedHills,
            "taiga_hills" => Self::TaigaHills,
            "mountain_edge" => Self::MountainEdge,
            "jungle" => Self::Jungle,
            "jungle_hills" => Self::JungleHills,
            "sparse_jungle" => Self::SparseJungle,
            "deep_ocean" => Self::DeepOcean,
            "stony_shore" => Self::StonyShore,
            "snowy_beach" => Self::SnowyBeach,
            "birch_forest" => Self::BirchForest,
            "birch_forest_hills" => Self::BirchForestHills,
            "dark_forest" => Self::DarkForest,
            "snowy_taiga" => Self::SnowyTaiga,
            "snowy_taiga_hills" => Self::SnowyTaigaHills,
            "old_growth_pine_taiga" => Self::OldGrowthPineTaiga,
            "old_growth_pine_taiga_hills" => Self::OldGrowthPineTaigaHills,
            "windswept_forest" => Self::WindsweptForest,
            "savanna" => Self::Savanna,
            "savanna_plateau" => Self::SavannaPlateau,
            "badlands" => Self::Badlands,
            "wooded_badlands" => Self::WoodedBadlands,
            "badlands_plateau" => Self::BadlandsPlateau,
            "small_end_islands" => Self::SmallEndIslands,
            "end_midlands" => Self::EndMidlands,
            "end_highlands" => Self::EndHighlands,
            "end_barrens" => Self::EndBarrens,
            "warm_ocean" => Self::WarmOcean,
            "lukewarm_ocean" => Self::LukewarmOcean,
            "cold_ocean" => Self::ColdOcean,
            "deep_warm_ocean" => Self::DeepWarmOcean,
            "deep_lukewarm_ocean" => Self::DeepLukewarmOcean,
            "deep_cold_ocean" => Self::DeepColdOcean,
            "deep_frozen_ocean" => Self::DeepFrozenOcean,
            "the_void" => Self::TheVoid,
            "sunflower_plains" => Self::SunflowerPlains,
            "gravelly_mountains" => Self::GravellyMountains,
            "flower_forest" => Self::FlowerForest,
            "ice_spikes" => Self::IceSpikes,
            "tall_birch_forest" => Self::TallBirchForest,
            "old_growth_spruce_taiga" => Self::OldGrowthSpruceTaiga,
            "windswept_savanna" => Self::WindsweptSavanna,
            "eroded_badlands" => Self::ErodedBadlands,
            "bamboo_jungle" => Self::BambooJungle,
            "soul_sand_valley" => Self::SoulSandValley,
            "crimson_forest" => Self::CrimsonForest,
            "warped_forest" => Self::WarpedForest,
            "basalt_deltas" => Self::BasaltDeltas,
            "dripstone_caves" => Self::DripstoneCaves,
            "lush_caves" => Self::LushCaves,
            "meadow" => Self::Meadow,
            "grove" => Self::Grove,
            "snowy_slopes" => Self::SnowySlopes,
            "jagged_peaks" => Self::JaggedPeaks,
            "frozen_peaks" => Self::FrozenPeaks,
            "stony_peaks" => Self::StonyPeaks,
            "deep_dark" => Self::DeepDark,
            "mangrove_swamp" => Self::MangroveSwamp,
            "cherry_grove" => Self::CherryGrove,
            "pale_garden" => Self::PaleGarden,
            _ => return None,
        })
    }
}
