// Generated by valentine_gen
// Do not edit: see crates/valentine_gen for generator.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_imports)]
//! Protocol modules
//!
//! One module per unique protocol version (some MC versions share one).
//! Prefer using `bedrock::version::vX_Y_Z` which re-exports the right protocol.
#[cfg(feature = "bedrock_0_14")]
pub mod v0_14;
#[cfg(feature = "bedrock_0_15")]
pub mod v0_15;
#[cfg(feature = "bedrock_1_16_201")]
pub mod v1_16_201;
#[cfg(feature = "bedrock_1_16_210")]
pub mod v1_16_210;
#[cfg(feature = "bedrock_1_16_220")]
pub mod v1_16_220;
#[cfg(feature = "bedrock_1_17_0")]
pub mod v1_17_0;
#[cfg(feature = "bedrock_1_17_10")]
pub mod v1_17_10;
#[cfg(feature = "bedrock_1_17_30")]
pub mod v1_17_30;
#[cfg(feature = "bedrock_1_17_40")]
pub mod v1_17_40;
#[cfg(feature = "bedrock_1_18_0")]
pub mod v1_18_0;
#[cfg(feature = "bedrock_1_18_11")]
pub mod v1_18_11;
#[cfg(feature = "bedrock_1_18_30")]
pub mod v1_18_30;
#[cfg(feature = "bedrock_1_19_1")]
pub mod v1_19_1;
#[cfg(feature = "bedrock_1_19_10")]
pub mod v1_19_10;
#[cfg(feature = "bedrock_1_19_20")]
pub mod v1_19_20;
#[cfg(feature = "bedrock_1_19_21")]
pub mod v1_19_21;
#[cfg(feature = "bedrock_1_19_30")]
pub mod v1_19_30;
#[cfg(feature = "bedrock_1_19_40")]
pub mod v1_19_40;
#[cfg(feature = "bedrock_1_19_50")]
pub mod v1_19_50;
#[cfg(feature = "bedrock_1_19_60")]
pub mod v1_19_60;
#[cfg(any(feature = "bedrock_1_19_62", feature = "bedrock_1_19_63"))]
pub mod v1_19_62;
#[cfg(feature = "bedrock_1_19_70")]
pub mod v1_19_70;
#[cfg(feature = "bedrock_1_19_80")]
pub mod v1_19_80;
#[cfg(feature = "bedrock_1_20_0")]
pub mod v1_20_0;
#[cfg(any(feature = "bedrock_1_20_10", feature = "bedrock_1_20_15"))]
pub mod v1_20_10;
#[cfg(feature = "bedrock_1_20_30")]
pub mod v1_20_30;
#[cfg(feature = "bedrock_1_20_40")]
pub mod v1_20_40;
#[cfg(feature = "bedrock_1_20_50")]
pub mod v1_20_50;
#[cfg(feature = "bedrock_1_20_61")]
pub mod v1_20_61;
#[cfg(feature = "bedrock_1_20_71")]
pub mod v1_20_71;
#[cfg(feature = "bedrock_1_20_80")]
pub mod v1_20_80;
#[cfg(feature = "bedrock_1_21_0")]
pub mod v1_21_0;
#[cfg(feature = "bedrock_1_21_100")]
pub mod v1_21_100;
#[cfg(feature = "bedrock_1_21_111")]
pub mod v1_21_111;
#[cfg(feature = "bedrock_1_21_120")]
pub mod v1_21_120;
#[cfg(feature = "bedrock_1_21_124")]
pub mod v1_21_124;
#[cfg(feature = "bedrock_1_21_2")]
pub mod v1_21_2;
#[cfg(feature = "bedrock_1_21_20")]
pub mod v1_21_20;
#[cfg(feature = "bedrock_1_21_30")]
pub mod v1_21_30;
#[cfg(feature = "bedrock_1_21_42")]
pub mod v1_21_42;
#[cfg(feature = "bedrock_1_21_50")]
pub mod v1_21_50;
#[cfg(feature = "bedrock_1_21_60")]
pub mod v1_21_60;
#[cfg(feature = "bedrock_1_21_70")]
pub mod v1_21_70;
#[cfg(feature = "bedrock_1_21_80")]
pub mod v1_21_80;
#[cfg(feature = "bedrock_1_21_90")]
pub mod v1_21_90;
#[cfg(feature = "bedrock_1_21_93")]
pub mod v1_21_93;
