// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
use bitflags::bitflags;
use super::*;
#[derive(Debug, Clone, PartialEq)]
pub struct Skin {
    pub skintype: String,
    pub texture: Vec<u8>,
}
impl crate::bedrock::codec::BedrockCodec for Skin {
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        self.skintype.encode(buf)?;
        self.texture.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(buf: &mut B) -> Result<Self, std::io::Error> {
        let skintype = <String as crate::bedrock::codec::BedrockCodec>::decode(buf)?;
        let texture = <Vec<u8> as crate::bedrock::codec::BedrockCodec>::decode(buf)?;
        Ok(Self { skintype, texture })
    }
}
