// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(clippy::all)]
use ::bitflags::bitflags;
use bytes::{Buf, BufMut};
use super::*;
use super::super::types::*;
use crate::bedrock::codec::BedrockCodec;
#[derive(Debug, Clone, PartialEq)]
pub struct PacketClientboundMapItemDataTracked {
    pub objects: Vec<TrackedObject>,
    pub decorations: Vec<MapDecoration>,
}
impl crate::bedrock::codec::BedrockCodec for PacketClientboundMapItemDataTracked {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        let len = self.objects.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        for item in &self.objects {
            item.encode(buf)?;
        }
        let len = self.decorations.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        for item in &self.decorations {
            item.encode(buf)?;
        }
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let objects = {
            let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0 as i64;
            if raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "array length cannot be negative",
                    ),
                );
            }
            let len = raw as usize;
            let mut tmp_vec = Vec::with_capacity(len);
            for _ in 0..len {
                tmp_vec
                    .push(
                        <TrackedObject as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    );
            }
            tmp_vec
        };
        let decorations = {
            let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0 as i64;
            if raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "array length cannot be negative",
                    ),
                );
            }
            let len = raw as usize;
            let mut tmp_vec = Vec::with_capacity(len);
            for _ in 0..len {
                tmp_vec
                    .push(
                        <MapDecoration as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    );
            }
            tmp_vec
        };
        Ok(Self { objects, decorations })
    }
}
#[derive(Debug, Clone, PartialEq)]
pub struct PacketClientboundMapItemDataTexture {
    pub width: i32,
    pub height: i32,
    pub x_offset: i32,
    pub y_offset: i32,
    pub pixels: Vec<i32>,
}
impl crate::bedrock::codec::BedrockCodec for PacketClientboundMapItemDataTexture {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        crate::bedrock::codec::ZigZag32(self.width).encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.height).encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.x_offset).encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.y_offset).encode(buf)?;
        let len = self.pixels.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        for item in &self.pixels {
            crate::bedrock::codec::VarInt(*item).encode(buf)?;
        }
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let width = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let height = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let x_offset = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let y_offset = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let pixels = {
            let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0 as i64;
            if raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "array length cannot be negative",
                    ),
                );
            }
            let len = raw as usize;
            let mut tmp_vec = Vec::with_capacity(len);
            for _ in 0..len {
                tmp_vec
                    .push(
                        <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                                buf,
                                (),
                            )?
                            .0,
                    );
            }
            tmp_vec
        };
        Ok(Self {
            width,
            height,
            x_offset,
            y_offset,
            pixels,
        })
    }
}
#[derive(Debug, Clone, PartialEq)]
pub struct PacketClientboundMapItemData {
    pub map_id: i64,
    pub update_flags: UpdateMapFlags,
    pub dimension: u8,
    pub locked: bool,
    pub included_in: Option<Vec<i64>>,
    pub scale: Option<u8>,
    pub tracked: Option<PacketClientboundMapItemDataTracked>,
    pub texture: Option<Box<PacketClientboundMapItemDataTexture>>,
}
impl crate::bedrock::codec::BedrockCodec for PacketClientboundMapItemData {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        crate::bedrock::codec::ZigZag64(self.map_id).encode(buf)?;
        self.update_flags.encode(buf)?;
        self.dimension.encode(buf)?;
        self.locked.encode(buf)?;
        if let Some(v) = &self.included_in {
            v.encode(buf)?;
        }
        if let Some(v) = &self.scale {
            v.encode(buf)?;
        }
        if let Some(v) = &self.tracked {
            v.encode(buf)?;
        }
        if let Some(v) = &self.texture {
            v.encode(buf)?;
        }
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let map_id = <crate::bedrock::codec::ZigZag64 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let update_flags = <UpdateMapFlags as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let dimension = <u8 as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let locked = <bool as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let included_in = if update_flags.contains(UpdateMapFlags::INITIALISATION) {
            Some({
                let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                        buf,
                        (),
                    )?
                    .0 as i64;
                if raw < 0 {
                    return Err(
                        std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            "array length cannot be negative",
                        ),
                    );
                }
                let len = raw as usize;
                let mut tmp_vec = Vec::with_capacity(len);
                for _ in 0..len {
                    tmp_vec
                        .push(
                            <crate::bedrock::codec::ZigZag64 as crate::bedrock::codec::BedrockCodec>::decode(
                                    buf,
                                    (),
                                )?
                                .0,
                        );
                }
                tmp_vec
            })
        } else {
            None
        };
        let scale = if (update_flags.contains(UpdateMapFlags::INITIALISATION)
            || update_flags.contains(UpdateMapFlags::DECORATION)
            || update_flags.contains(UpdateMapFlags::TEXTURE))
        {
            Some(<u8 as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?)
        } else {
            None
        };
        let tracked = if update_flags.contains(UpdateMapFlags::DECORATION) {
            Some(
                <PacketClientboundMapItemDataTracked as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?,
            )
        } else {
            None
        };
        let texture = if update_flags.contains(UpdateMapFlags::TEXTURE) {
            Some(
                Box::new(
                    <PacketClientboundMapItemDataTexture as crate::bedrock::codec::BedrockCodec>::decode(
                        buf,
                        (),
                    )?,
                ),
            )
        } else {
            None
        };
        Ok(Self {
            map_id,
            update_flags,
            dimension,
            locked,
            included_in,
            scale,
            tracked,
            texture,
        })
    }
}
