// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
use ::bitflags::bitflags;
use super::*;
use super::super::types::*;
use crate::bedrock::codec::BedrockCodec;
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum PacketBookEditType {
    ReplacePage = 0,
    AddPage = 1,
    DeletePage = 2,
    SwapPages = 3,
    Sign = 4,
}
impl crate::bedrock::codec::BedrockCodec for PacketBookEditType {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = *self as u8;
        val.encode(buf)
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let val = <u8 as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        match val {
            0 => Ok(PacketBookEditType::ReplacePage),
            1 => Ok(PacketBookEditType::AddPage),
            2 => Ok(PacketBookEditType::DeletePage),
            3 => Ok(PacketBookEditType::SwapPages),
            4 => Ok(PacketBookEditType::Sign),
            _ => {
                Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        format!(
                            "Invalid enum value for {}: {}",
                            stringify!(PacketBookEditType), val
                        ),
                    ),
                )
            }
        }
    }
}
#[derive(Debug, Clone, PartialEq)]
pub struct PacketBookEditContentAddPage {
    pub page_number: u8,
    pub text: String,
    pub photo_name: String,
}
impl crate::bedrock::codec::BedrockCodec for PacketBookEditContentAddPage {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.page_number.encode(buf)?;
        self.text.encode(buf)?;
        self.photo_name.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let page_number = <u8 as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let text = <String as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let photo_name = <String as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        Ok(Self {
            page_number,
            text,
            photo_name,
        })
    }
}
#[derive(Debug, Clone, PartialEq)]
pub struct PacketBookEditContentDeletePage {
    pub page_number: u8,
}
impl crate::bedrock::codec::BedrockCodec for PacketBookEditContentDeletePage {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.page_number.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let page_number = <u8 as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        Ok(Self { page_number })
    }
}
#[derive(Debug, Clone, PartialEq)]
pub struct PacketBookEditContentSign {
    pub title: String,
    pub author: String,
    pub xuid: String,
}
impl crate::bedrock::codec::BedrockCodec for PacketBookEditContentSign {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.title.encode(buf)?;
        self.author.encode(buf)?;
        self.xuid.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let title = <String as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let author = <String as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let xuid = <String as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        Ok(Self { title, author, xuid })
    }
}
#[derive(Debug, Clone, PartialEq)]
pub struct PacketBookEditContentSwapPages {
    pub page_1: u8,
    pub page_2: u8,
}
impl crate::bedrock::codec::BedrockCodec for PacketBookEditContentSwapPages {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.page_1.encode(buf)?;
        self.page_2.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let page_1 = <u8 as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let page_2 = <u8 as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        Ok(Self { page_1, page_2 })
    }
}
#[derive(Debug, Clone, PartialEq)]
pub enum PacketBookEditContent {
    AddPage(PacketBookEditContentAddPage),
    DeletePage(PacketBookEditContentDeletePage),
    ReplacePage(PacketBookEditContentAddPage),
    Sign(PacketBookEditContentSign),
    SwapPages(PacketBookEditContentSwapPages),
}
#[derive(Debug, Clone, PartialEq)]
pub struct PacketBookEdit {
    pub type_: PacketBookEditType,
    pub slot: u8,
    pub content: Option<PacketBookEditContent>,
}
impl crate::bedrock::codec::BedrockCodec for PacketBookEdit {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.type_.encode(buf)?;
        self.slot.encode(buf)?;
        if let Some(v) = &self.content {
            match v {
                PacketBookEditContent::AddPage(v) => {
                    v.encode(buf)?;
                }
                PacketBookEditContent::DeletePage(v) => {
                    v.encode(buf)?;
                }
                PacketBookEditContent::ReplacePage(v) => {
                    v.encode(buf)?;
                }
                PacketBookEditContent::Sign(v) => {
                    v.encode(buf)?;
                }
                PacketBookEditContent::SwapPages(v) => {
                    v.encode(buf)?;
                }
            }
        }
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let type_ = <PacketBookEditType as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let slot = <u8 as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let content = match type_ {
            PacketBookEditType::AddPage => {
                Some(
                    PacketBookEditContent::AddPage(
                        <PacketBookEditContentAddPage as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    ),
                )
            }
            PacketBookEditType::DeletePage => {
                Some(
                    PacketBookEditContent::DeletePage(
                        <PacketBookEditContentDeletePage as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    ),
                )
            }
            PacketBookEditType::ReplacePage => {
                Some(
                    PacketBookEditContent::ReplacePage(
                        <PacketBookEditContentAddPage as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    ),
                )
            }
            PacketBookEditType::Sign => {
                Some(
                    PacketBookEditContent::Sign(
                        <PacketBookEditContentSign as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    ),
                )
            }
            PacketBookEditType::SwapPages => {
                Some(
                    PacketBookEditContent::SwapPages(
                        <PacketBookEditContentSwapPages as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    ),
                )
            }
        };
        Ok(Self { type_, slot, content })
    }
}
