// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(clippy::all)]
use ::bitflags::bitflags;
use bytes::{Buf, BufMut};
use super::*;
use super::super::types::*;
use crate::bedrock::codec::BedrockCodec;
#[derive(Debug, Clone, PartialEq)]
pub struct PacketCommandRequest {
    pub command: String,
    pub origin: CommandOrigin,
    pub internal: bool,
    pub version: i32,
}
impl crate::bedrock::codec::BedrockCodec for PacketCommandRequest {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.command)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.command).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        self.origin.encode(buf)?;
        self.internal.encode(buf)?;
        crate::bedrock::codec::VarInt(self.version).encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let command = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let origin = <CommandOrigin as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let internal = <bool as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        let version = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        Ok(Self {
            command,
            origin,
            internal,
            version,
        })
    }
}
pub use crate::bedrock::protocol::v1_16_201::PacketCommandBlockUpdate as PacketCommandBlockUpdate;
pub use crate::bedrock::protocol::v1_16_201::PacketCommandBlockUpdateContent as PacketCommandBlockUpdateContent;
pub use crate::bedrock::protocol::v1_16_201::PacketCommandBlockUpdateContentFalse as PacketCommandBlockUpdateContentFalse;
pub use crate::bedrock::protocol::v1_16_201::PacketCommandBlockUpdateContentTrue as PacketCommandBlockUpdateContentTrue;
pub use crate::bedrock::protocol::v1_16_201::PacketCommandBlockUpdateContentTrueMode as PacketCommandBlockUpdateContentTrueMode;
pub use crate::bedrock::protocol::v1_18_11::PacketCommandOutput as PacketCommandOutput;
pub use crate::bedrock::protocol::v1_18_11::PacketCommandOutputOutputItem as PacketCommandOutputOutputItem;
pub use crate::bedrock::protocol::v1_18_11::PacketCommandOutputOutputType as PacketCommandOutputOutputType;
