// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(clippy::all)]
use ::bitflags::bitflags;
use bytes::{Buf, BufMut};
use super::*;
use super::super::types::*;
use crate::bedrock::codec::BedrockCodec;
pub use crate::bedrock::protocol::v1_16_201::PacketItemFrameDropItem as PacketItemFrameDropItem;
#[derive(Debug, Clone, PartialEq)]
pub struct PacketItemStackRequest {
    pub requests: Vec<ItemStackRequest>,
}
#[derive(Debug, Clone)]
pub struct PacketItemStackRequestArgs {
    pub shield_item_id: i32,
}
impl<'a> From<&'a crate::bedrock::context::BedrockSession>
for PacketItemStackRequestArgs {
    fn from(source: &'a crate::bedrock::context::BedrockSession) -> Self {
        Self {
            shield_item_id: source.shield_item_id,
        }
    }
}
impl crate::bedrock::codec::BedrockCodec for PacketItemStackRequest {
    type Args = PacketItemStackRequestArgs;
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        let len = self.requests.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        for item in &self.requests {
            item.encode(buf)?;
        }
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let requests = {
            let raw = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0 as i64;
            if raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "array length cannot be negative",
                    ),
                );
            }
            let len = raw as usize;
            let mut tmp_vec = Vec::with_capacity(len);
            for _ in 0..len {
                tmp_vec
                    .push(
                        <ItemStackRequest as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            ItemStackRequestArgs {
                                shield_item_id: args.shield_item_id,
                            },
                        )?,
                    );
            }
            tmp_vec
        };
        Ok(Self { requests })
    }
}
pub use crate::bedrock::protocol::v1_19_50::PacketItemStackResponse as PacketItemStackResponse;
pub use crate::bedrock::protocol::v1_16_201::PacketItemComponent as PacketItemComponent;
