// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
use bitflags::bitflags;
use super::*;
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum Action {
    StartBreak = 0,
    AbortBreak = 1,
    StopBreak = 2,
    GetUpdatedBlock = 3,
    DropItem = 4,
    StartSleeping = 5,
    StopSleeping = 6,
    Respawn = 7,
    Jump = 8,
    StartSprint = 9,
    StopSprint = 10,
    StartSneak = 11,
    StopSneak = 12,
    CreativePlayerDestroyBlock = 13,
    DimensionChangeAck = 14,
    StartGlide = 15,
    StopGlide = 16,
    BuildDenied = 17,
    CrackBreak = 18,
    ChangeSkin = 19,
    SetEnchatnmentSeed = 20,
    Swimming = 21,
    StopSwimming = 22,
    StartSpinAttack = 23,
    StopSpinAttack = 24,
    InteractBlock = 25,
    PredictBreak = 26,
    ContinueBreak = 27,
    StartItemUseOn = 28,
    StopItemUseOn = 29,
    HandledTeleport = 30,
    MissedSwing = 31,
    StartCrawling = 32,
    StopCrawling = 33,
}
impl crate::bedrock::codec::BedrockCodec for Action {
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = *self as i32;
        val.encode(buf)
    }
    fn decode<B: bytes::Buf>(buf: &mut B) -> Result<Self, std::io::Error> {
        let val = <i32 as crate::bedrock::codec::BedrockCodec>::decode(buf)?;
        match val {
            0 => Ok(Action::StartBreak),
            1 => Ok(Action::AbortBreak),
            2 => Ok(Action::StopBreak),
            3 => Ok(Action::GetUpdatedBlock),
            4 => Ok(Action::DropItem),
            5 => Ok(Action::StartSleeping),
            6 => Ok(Action::StopSleeping),
            7 => Ok(Action::Respawn),
            8 => Ok(Action::Jump),
            9 => Ok(Action::StartSprint),
            10 => Ok(Action::StopSprint),
            11 => Ok(Action::StartSneak),
            12 => Ok(Action::StopSneak),
            13 => Ok(Action::CreativePlayerDestroyBlock),
            14 => Ok(Action::DimensionChangeAck),
            15 => Ok(Action::StartGlide),
            16 => Ok(Action::StopGlide),
            17 => Ok(Action::BuildDenied),
            18 => Ok(Action::CrackBreak),
            19 => Ok(Action::ChangeSkin),
            20 => Ok(Action::SetEnchatnmentSeed),
            21 => Ok(Action::Swimming),
            22 => Ok(Action::StopSwimming),
            23 => Ok(Action::StartSpinAttack),
            24 => Ok(Action::StopSpinAttack),
            25 => Ok(Action::InteractBlock),
            26 => Ok(Action::PredictBreak),
            27 => Ok(Action::ContinueBreak),
            28 => Ok(Action::StartItemUseOn),
            29 => Ok(Action::StopItemUseOn),
            30 => Ok(Action::HandledTeleport),
            31 => Ok(Action::MissedSwing),
            32 => Ok(Action::StartCrawling),
            33 => Ok(Action::StopCrawling),
            _ => {
                Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        format!("Invalid enum value for {}: {}", stringify!(Action), val),
                    ),
                )
            }
        }
    }
}
bitflags! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)] pub struct InputFlag : u64 { const
    ASCEND = 1; const DESCEND = 2; const NORTH_JUMP = 4; const JUMP_DOWN = 8; const
    SPRINT_DOWN = 16; const CHANGE_HEIGHT = 32; const JUMPING = 64; const
    AUTO_JUMPING_IN_WATER = 128; const SNEAKING = 256; const SNEAK_DOWN = 512; const UP =
    1024; const DOWN = 2048; const LEFT = 4096; const RIGHT = 8192; const UP_LEFT =
    16384; const UP_RIGHT = 32768; const WANT_UP = 65536; const WANT_DOWN = 131072; const
    WANT_DOWN_SLOW = 262144; const WANT_UP_SLOW = 524288; const SPRINTING = 1048576;
    const ASCEND_BLOCK = 2097152; const DESCEND_BLOCK = 4194304; const SNEAK_TOGGLE_DOWN
    = 8388608; const PERSIST_SNEAK = 16777216; const START_SPRINTING = 33554432; const
    STOP_SPRINTING = 67108864; const START_SNEAKING = 134217728; const STOP_SNEAKING =
    268435456; const START_SWIMMING = 536870912; const STOP_SWIMMING = 1073741824; const
    START_JUMPING = 2147483648; const START_GLIDING = 4294967296; const STOP_GLIDING =
    8589934592; const ITEM_INTERACT = 17179869184; const BLOCK_ACTION = 34359738368;
    const ITEM_STACK_REQUEST = 68719476736; const HANDLED_TELEPORT = 137438953472; const
    EMOTING = 274877906944; const MISSED_SWING = 549755813888; const START_CRAWLING =
    1099511627776; const STOP_CRAWLING = 2199023255552; }
}
impl crate::bedrock::codec::BedrockCodec for InputFlag {
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = self.bits();
        (val as i64).encode(buf)
    }
    fn decode<B: bytes::Buf>(buf: &mut B) -> Result<Self, std::io::Error> {
        let raw = <i64 as crate::bedrock::codec::BedrockCodec>::decode(buf)?;
        let bits = raw as u64;
        Ok(Self::from_bits_retain(bits))
    }
}
bitflags! {
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)] pub struct MetadataFlags2 : u64 {
    const SNEEZING = 1; const TRUSTING = 2; const ROLLING = 4; const SCARED = 8; const
    IN_SCAFFOLDING = 16; const OVER_SCAFFOLDING = 32; const FALL_THROUGH_SCAFFOLDING =
    64; const BLOCKING = 128; const TRANSITION_BLOCKING = 256; const BLOCKED_USING_SHIELD
    = 512; const BLOCKED_USING_DAMAGED_SHIELD = 1024; const SLEEPING = 2048; const
    WANTS_TO_WAKE = 4096; const TRADE_INTEREST = 8192; const DOOR_BREAKER = 16384; const
    BREAKING_OBSTRUCTION = 32768; const DOOR_OPENER = 65536; const ILLAGER_CAPTAIN =
    131072; const STUNNED = 262144; const ROARING = 524288; const DELAYED_ATTACKING =
    1048576; const AVOIDING_MOBS = 2097152; const AVOIDING_BLOCK = 4194304; const
    FACING_TARGET_TO_RANGE_ATTACK = 8388608; const HIDDEN_WHEN_INVISIBLE = 16777216;
    const IS_IN_UI = 33554432; const STALKING = 67108864; const EMOTING = 134217728;
    const CELEBRATING = 268435456; const ADMIRING = 536870912; const CELEBRATING_SPECIAL
    = 1073741824; const UNKNOWN95 = 2147483648; const RAM_ATTACK = 4294967296; const
    PLAYING_DEAD = 8589934592; const IN_ASCENDABLE_BLOCK = 17179869184; const
    OVER_DESCENDABLE_BLOCK = 34359738368; const CROAKING = 68719476736; const EAT_MOB =
    137438953472; const JUMP_GOAL_JUMP = 274877906944; const EMERGING = 549755813888;
    const SNIFFING = 1099511627776; const DIGGING = 2199023255552; const SONIC_BOOM =
    4398046511104; const HAS_DASH_COOLDOWN = 8796093022208; const
    PUSH_TOWARDS_CLOSEST_SPACE = 17592186044416; const SCENTING = 35184372088832; const
    RISING = 70368744177664; const FEELING_HAPPY = 140737488355328; const SEARCHING =
    281474976710656; const CRAWLING = 562949953421312; }
}
impl crate::bedrock::codec::BedrockCodec for MetadataFlags2 {
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = self.bits();
        crate::bedrock::codec::ZigZag64(val as i64).encode(buf)
    }
    fn decode<B: bytes::Buf>(buf: &mut B) -> Result<Self, std::io::Error> {
        let raw = <crate::bedrock::codec::ZigZag64 as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
        )?;
        let bits = raw.0 as u64;
        Ok(Self::from_bits_retain(bits))
    }
}
pub type MetadataDictionary = Vec<MetadataDictionaryItem>;
