// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(clippy::all)]
use ::bitflags::bitflags;
use bytes::{Buf, BufMut};
use super::*;
use super::super::types::*;
use crate::bedrock::codec::BedrockCodec;
#[derive(Debug, Clone, PartialEq, Default)]
pub struct PacketNetworkStackLatency {
    pub timestamp: u64,
    pub needs_response: u8,
}
impl crate::bedrock::codec::BedrockCodec for PacketNetworkStackLatency {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        crate::bedrock::codec::U64LE(self.timestamp).encode(buf)?;
        self.needs_response.encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let timestamp = <crate::bedrock::codec::U64LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let needs_response = <u8 as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        Ok(Self { timestamp, needs_response })
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct PacketNetworkChunkPublisherUpdateSavedChunksItem {
    pub x: i32,
    pub z: i32,
}
impl crate::bedrock::codec::BedrockCodec
for PacketNetworkChunkPublisherUpdateSavedChunksItem {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        crate::bedrock::codec::ZigZag32(self.x).encode(buf)?;
        crate::bedrock::codec::ZigZag32(self.z).encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let x = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let z = <crate::bedrock::codec::ZigZag32 as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        Ok(Self { x, z })
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct PacketNetworkChunkPublisherUpdate {
    pub coordinates: BlockCoordinates,
    pub radius: i32,
    pub saved_chunks: Vec<PacketNetworkChunkPublisherUpdateSavedChunksItem>,
}
impl crate::bedrock::codec::BedrockCodec for PacketNetworkChunkPublisherUpdate {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        self.coordinates.encode(buf)?;
        crate::bedrock::codec::VarInt(self.radius).encode(buf)?;
        let len = self.saved_chunks.len();
        crate::bedrock::codec::U32LE(len as u32).encode(buf)?;
        for item in &self.saved_chunks {
            item.encode(buf)?;
        }
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let coordinates = <BlockCoordinates as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let radius = <crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let saved_chunks = {
            let len = (<crate::bedrock::codec::U32LE as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as usize;
            let mut tmp_vec = Vec::with_capacity(len);
            for _ in 0..len {
                tmp_vec
                    .push(
                        <PacketNetworkChunkPublisherUpdateSavedChunksItem as crate::bedrock::codec::BedrockCodec>::decode(
                            buf,
                            (),
                        )?,
                    );
            }
            tmp_vec
        };
        Ok(Self {
            coordinates,
            radius,
            saved_chunks,
        })
    }
}
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u16)]
pub enum PacketNetworkSettingsCompressionAlgorithm {
    Deflate = 0,
    Snappy = 1,
}
impl crate::bedrock::codec::BedrockCodec for PacketNetworkSettingsCompressionAlgorithm {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = *self as u16;
        crate::bedrock::codec::U16LE(val as u16).encode(buf)
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let raw = <crate::bedrock::codec::U16LE as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let val = raw.0 as u16;
        match val {
            0 => Ok(PacketNetworkSettingsCompressionAlgorithm::Deflate),
            1 => Ok(PacketNetworkSettingsCompressionAlgorithm::Snappy),
            _ => {
                Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        format!(
                            "Invalid enum value for {}: {}",
                            stringify!(PacketNetworkSettingsCompressionAlgorithm), val
                        ),
                    ),
                )
            }
        }
    }
}
impl Default for PacketNetworkSettingsCompressionAlgorithm {
    fn default() -> Self {
        Self::Deflate
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct PacketNetworkSettings {
    pub compression_threshold: u16,
    pub compression_algorithm: PacketNetworkSettingsCompressionAlgorithm,
    pub client_throttle: bool,
    pub client_throttle_threshold: u8,
    pub client_throttle_scalar: f32,
}
impl crate::bedrock::codec::BedrockCodec for PacketNetworkSettings {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        crate::bedrock::codec::U16LE(self.compression_threshold).encode(buf)?;
        self.compression_algorithm.encode(buf)?;
        self.client_throttle.encode(buf)?;
        self.client_throttle_threshold.encode(buf)?;
        crate::bedrock::codec::F32LE(self.client_throttle_scalar).encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let compression_threshold = <crate::bedrock::codec::U16LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let compression_algorithm = <PacketNetworkSettingsCompressionAlgorithm as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let client_throttle = <bool as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let client_throttle_threshold = <u8 as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let client_throttle_scalar = <crate::bedrock::codec::F32LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        Ok(Self {
            compression_threshold,
            compression_algorithm,
            client_throttle,
            client_throttle_threshold,
            client_throttle_scalar,
        })
    }
}
