// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(clippy::all)]
use ::bitflags::bitflags;
use bytes::{Buf, BufMut};
use super::*;
use super::super::types::*;
use crate::bedrock::codec::BedrockCodec;
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum PacketVideoStreamConnectAction {
    None = 1,
    Close = 2,
}
impl crate::bedrock::codec::BedrockCodec for PacketVideoStreamConnectAction {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let val = *self as u8;
        val.encode(buf)
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let val = <u8 as crate::bedrock::codec::BedrockCodec>::decode(buf, ())?;
        match val {
            1 => Ok(PacketVideoStreamConnectAction::None),
            2 => Ok(PacketVideoStreamConnectAction::Close),
            _ => {
                Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        format!(
                            "Invalid enum value for {}: {}",
                            stringify!(PacketVideoStreamConnectAction), val
                        ),
                    ),
                )
            }
        }
    }
}
impl Default for PacketVideoStreamConnectAction {
    fn default() -> Self {
        Self::None
    }
}
#[derive(Debug, Clone, PartialEq, Default)]
pub struct PacketVideoStreamConnect {
    pub server_uri: String,
    pub frame_send_frequency: f32,
    pub action: PacketVideoStreamConnectAction,
    pub resolution_x: i32,
    pub resolution_y: i32,
}
impl crate::bedrock::codec::BedrockCodec for PacketVideoStreamConnect {
    type Args = ();
    fn encode<B: bytes::BufMut>(&self, buf: &mut B) -> Result<(), std::io::Error> {
        let _ = buf;
        let bytes: Vec<u8> = if "".eq_ignore_ascii_case("latin1") {
            (&self.server_uri)
                .chars()
                .map(|ch| {
                    let code = ch as u32;
                    if code <= 0xFF { code as u8 } else { b'?' }
                })
                .collect()
        } else {
            (&self.server_uri).as_bytes().to_vec()
        };
        let len = bytes.len();
        crate::bedrock::codec::VarInt(len as i32).encode(buf)?;
        buf.put_slice(&bytes);
        crate::bedrock::codec::F32LE(self.frame_send_frequency).encode(buf)?;
        self.action.encode(buf)?;
        crate::bedrock::codec::I32LE(self.resolution_x).encode(buf)?;
        crate::bedrock::codec::I32LE(self.resolution_y).encode(buf)?;
        Ok(())
    }
    fn decode<B: bytes::Buf>(
        buf: &mut B,
        _args: Self::Args,
    ) -> Result<Self, std::io::Error> {
        let _ = buf;
        let server_uri = {
            let len_raw = (<crate::bedrock::codec::VarInt as crate::bedrock::codec::BedrockCodec>::decode(
                    buf,
                    (),
                )?
                .0) as i64;
            if len_raw < 0 {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::InvalidData,
                        "string length cannot be negative",
                    ),
                );
            }
            let len = len_raw as usize;
            if buf.remaining() < len {
                return Err(
                    std::io::Error::new(
                        std::io::ErrorKind::UnexpectedEof,
                        format!(
                            "string declared length {} exceeds remaining {}", len, buf
                            .remaining()
                        ),
                    ),
                );
            }
            let mut bytes = vec![0u8; len];
            buf.copy_to_slice(&mut bytes);
            let s = if "".eq_ignore_ascii_case("latin1") {
                bytes.into_iter().map(|b| b as char).collect::<String>()
            } else {
                String::from_utf8_lossy(&bytes).into_owned()
            };
            s
        };
        let frame_send_frequency = <crate::bedrock::codec::F32LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let action = <PacketVideoStreamConnectAction as crate::bedrock::codec::BedrockCodec>::decode(
            buf,
            (),
        )?;
        let resolution_x = <crate::bedrock::codec::I32LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        let resolution_y = <crate::bedrock::codec::I32LE as crate::bedrock::codec::BedrockCodec>::decode(
                buf,
                (),
            )?
            .0;
        Ok(Self {
            server_uri,
            frame_send_frequency,
            action,
            resolution_x,
            resolution_y,
        })
    }
}
