// Generated by valentine_gen. Do not edit.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(clippy::all)]
use ::bitflags::bitflags;
use bytes::{Buf, BufMut};
use super::*;
use super::super::types::*;
use crate::bedrock::codec::BedrockCodec;
pub use crate::bedrock::protocol::v1_16_220::PacketInventoryTransaction as PacketInventoryTransaction;
pub use crate::bedrock::protocol::v1_16_220::PacketInventoryTransactionArgs as PacketInventoryTransactionArgs;
pub use crate::bedrock::protocol::v1_16_220::PacketInventoryContent as PacketInventoryContent;
pub use crate::bedrock::protocol::v1_16_220::PacketInventoryContentArgs as PacketInventoryContentArgs;
pub use crate::bedrock::protocol::v1_16_220::PacketInventorySlot as PacketInventorySlot;
pub use crate::bedrock::protocol::v1_16_220::PacketInventorySlotArgs as PacketInventorySlotArgs;
