//! Normalize Valentine block definitions into a golden KDL artifact.

use kdl::{KdlDocument, KdlEntry, KdlNode, KdlValue};
use std::path::Path;
use tracing::info;

pub fn write_blocks_kdl(output_dir: &Path) -> miette::Result<()> {
    let mut blocks: Vec<_> = valentine_bedrock_1_26_0::blocks::BLOCKS.to_vec();
    blocks.sort_by_key(|block| (block.min_state_id(), block.string_id()));

    let mut doc = KdlDocument::new();
    let mut state_id_count = 0u32;

    for block in &blocks {
        state_id_count += block_state_id_count(*block);

        let mut node = KdlNode::new("block");
        node.push(KdlEntry::new(KdlValue::String(
            block.string_id().to_string(),
        )));
        node.push(KdlEntry::new_prop(
            "id",
            KdlValue::Integer(block.id() as i128),
        ));
        node.push(KdlEntry::new_prop(
            "name",
            KdlValue::String(block.name().to_string()),
        ));
        node.push(KdlEntry::new_prop(
            "hardness",
            KdlValue::Float(readable_f32(block.hardness())),
        ));
        node.push(KdlEntry::new_prop(
            "resistance",
            KdlValue::Float(readable_f32(block.resistance())),
        ));
        node.push(KdlEntry::new_prop(
            "is_transparent",
            KdlValue::Bool(block.is_transparent()),
        ));
        node.push(KdlEntry::new_prop(
            "emit_light",
            KdlValue::Integer(block.emit_light() as i128),
        ));
        node.push(KdlEntry::new_prop(
            "filter_light",
            KdlValue::Integer(block.filter_light() as i128),
        ));
        node.push(KdlEntry::new_prop(
            "min_state_id",
            KdlValue::Integer(block.min_state_id() as i128),
        ));
        node.push(KdlEntry::new_prop(
            "max_state_id",
            KdlValue::Integer(block.max_state_id() as i128),
        ));
        node.push(KdlEntry::new_prop(
            "default_state_id",
            KdlValue::Integer(block.default_state_id() as i128),
        ));
        node.push(KdlEntry::new_prop(
            "state_id_count",
            KdlValue::Integer(block_state_id_count(*block) as i128),
        ));

        doc.nodes_mut().push(node);
    }

    write_kdl_with_header(
        output_dir,
        &format!(
            "// AUTO-GENERATED by unastar-data-gen\n\
             // Do not edit manually - changes will be overwritten\n\
             // Source: valentine_bedrock_1_26_0 generated block definitions\n\
             // Block count: {}\n\
             // Canonical state ID count: {}\n\n",
            blocks.len(),
            state_id_count
        ),
        doc,
    )?;

    info!(
        "Wrote {} Valentine block entries covering {} states",
        blocks.len(),
        state_id_count
    );
    Ok(())
}

fn block_state_id_count(block: &dyn valentine_bedrock_core::block::BlockDefDyn) -> u32 {
    block.max_state_id() - block.min_state_id() + 1
}

fn readable_f32(value: f32) -> f64 {
    (f64::from(value) * 1_000_000.0).round() / 1_000_000.0
}

fn write_kdl_with_header(
    output_dir: &Path,
    header: &str,
    mut doc: KdlDocument,
) -> miette::Result<()> {
    doc.autoformat();
    std::fs::create_dir_all(output_dir)
        .map_err(|e| miette::miette!("Failed to create {}: {}", output_dir.display(), e))?;
    let path = output_dir.join("blocks.kdl");
    std::fs::write(&path, format!("{header}{doc}"))
        .map_err(|e| miette::miette!("Failed to write {}: {}", path.display(), e))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn checked_in_blocks_artifact_parses_as_kdl() {
        include_str!("../../output/blocks.kdl")
            .parse::<KdlDocument>()
            .expect("generated blocks.kdl should parse");
    }

    #[test]
    fn valentine_block_ranges_are_contiguous_in_palette_order() {
        let mut blocks: Vec<_> = valentine_bedrock_1_26_0::blocks::BLOCKS.to_vec();
        blocks.sort_by_key(|block| (block.min_state_id(), block.string_id()));

        for window in blocks.windows(2) {
            let current = window[0];
            let next = window[1];
            assert_eq!(
                current.max_state_id() + 1,
                next.min_state_id(),
                "{} and {} should be adjacent in the canonical state palette",
                current.string_id(),
                next.string_id()
            );
        }
    }

    #[test]
    fn readable_floats_trim_generated_f32_noise() {
        assert_eq!(readable_f32(4.2_f32), 4.2);
    }

    #[test]
    fn state_id_count_uses_canonical_range_not_generated_state_type() {
        let fence_gate = valentine_bedrock_1_26_0::blocks::BLOCKS
            .iter()
            .copied()
            .find(|block| block.string_id() == "minecraft:fence_gate")
            .expect("fence_gate block exists");

        assert_eq!(block_state_id_count(fence_gate), 16);
    }

    #[test]
    fn checked_in_blocks_artifact_preserves_default_state_ids() {
        let doc: KdlDocument = include_str!("../../output/blocks.kdl")
            .parse()
            .expect("generated blocks.kdl should parse");

        let stone = doc
            .nodes()
            .iter()
            .find(|node| {
                node.entries()
                    .first()
                    .and_then(|entry| entry.value().as_string())
                    == Some("minecraft:stone")
            })
            .expect("stone entry exists");

        assert!(
            stone.get("default_state_id").is_some(),
            "blocks.kdl should expose default_state_id for registry consumers"
        );
    }
}
